// ============================================================
// lang.js — Système de traduction PeptideScanner
// FR + EN · Objet global window.PS_LANG
// Usage : <script src="/lang.js"></script>
// ============================================================

window.PS_LANG = {

  fr: {
    // ── NAV ──────────────────────────────────────────────────
    nav_home:       'Accueil',
    nav_cure:       'Cure',
    nav_calc:       'Calcul',
    nav_stock:      'Stock',
    nav_alerts:     'Alertes',
    nav_profile:    'Profil',
    nav_biblio:     'Biblio',
    nav_weight:     'Poids',
    nav_ia:         'IA',
    nav_analyse:    'Analyse',

    // ── COMMON ───────────────────────────────────────────────
    save:           'Enregistrer',
    cancel:         'Annuler',
    delete:         'Supprimer',
    edit:           'Modifier',
    add:            'Ajouter',
    confirm:        'Confirmer',
    close:          'Fermer',
    loading:        'Chargement…',
    error:          'Erreur',
    success:        'Succès',
    optional:       'optionnel',
    all:            'Tout',
    none:           'Aucun',
    days:           'jours',
    day:            'jour',
    today:          "Aujourd'hui",
    week:           'semaine',
    month:          'mois',
    yes:            'Oui',
    no:             'Non',
    back:           'Retour',
    next:           'Suivant',
    see_all:        'Voir tout →',
    details:        'Détail →',
    no_data:        'Aucune donnée',

    // ── DISCLAIMER ───────────────────────────────────────────
    disclaimer_short: 'Usage éducatif uniquement — Peptides de recherche non approuvés à usage humain. Consultez un professionnel de santé. PeptideScanner décline toute responsabilité.',
    disclaimer_icon:  '⚠️',

    // ── DASHBOARD ────────────────────────────────────────────
    dash_greeting:        'Bonjour 👋',
    dash_active_cure:     'Cure active',
    dash_protocol:        'Protocole en cours',
    dash_no_cure:         'Aucune cure active',
    dash_no_cure_sub:     'Appuyez sur "+ Nouvelle cure" pour commencer',
    dash_day_label:       '/ jours',
    dash_calendar:        '📅 Calendrier',
    dash_new_cure:        '＋ Nouvelle cure',
    dash_summary:         'Résumé',
    dash_weight_title:    'Évolution du poids',
    dash_today_section:   "Aujourd'hui",
    dash_calendar_link:   'Calendrier →',
    dash_alerts_section:  'Alertes récentes',
    dash_alerts_all:      'Toutes →',
    dash_no_alerts:       'Aucune alerte active 🎉',
    dash_weight_go:       'Poids →',
    dash_inj_done:        'Injections faites',
    dash_days_left:       'Jours restants',
    dash_end_date:        'Fin estimée',
    dash_compliance:      'Compliance',
    dash_cures_done:      'Cures complétées',
    dash_total_inj:       'Injections totales',
    dash_current_weight:  'Poids actuel',
    dash_since_start:     'depuis le début',
    dash_first_measure:   'Première mesure',
    dash_no_weight_data:  'Aucune donnée — Ajouter votre poids',
    dash_score_label:     'doses faites',
    dash_score_done:      '✅ Complété',
    dash_today_program:   'Programme du jour',
    dash_no_injection:    'Aucune injection prévue aujourd\'hui.',
    dash_injection_day:   'Injection du jour',
    dash_injection_num:   'Injection',
    dash_confirm_inj:     'Confirmer l\'injection',
    dash_check_time:      'Vérifiez l\'heure avant de valider',
    dash_inj_time:        '⏰ Heure d\'injection',
    dash_validate:        '✓ Valider l\'injection',
    dash_new_cure_title:  'Nouvelle cure',
    dash_peptide:         'Peptide',
    dash_choose_peptide:  'Choisir un peptide…',
    dash_dosage:          'Dosage',
    dash_admin:           'Administration',
    dash_start_date:      'Date de début',
    dash_duration:        'Durée (jours)',
    dash_frequency:       'Fréquence d\'injection',
    dash_start_cure:      'Démarrer la cure',
    dash_cure_ended:      'Fin de cure dans',
    dash_days_suffix:     'j',
    dash_inj_cancelled:   'Injection annulée',
    dash_inj_saved:       '— enregistré !',
    freq_1x:    '1× par jour',
    freq_2x:    '2× par jour',
    freq_3x:    '3× par jour',
    freq_1_2d:  '1× tous les 2 jours',
    freq_2x_w:  '2× par semaine',
    freq_1x_w:  '1× par semaine',
    admin_sc:   'SC',
    admin_im:   'IM',
    admin_oral: 'Oral',
    admin_nasal:'Nasal',
    admin_iv:   'IV',

    // ── CURE ─────────────────────────────────────────────────
    cure_title:         'Calendrier de cure',
    cure_status_active: 'En cours',
    cure_status_ended:  'Terminée',
    cure_status_future: 'À venir',
    cure_dosage:        'Dosage',
    cure_frequency:     'Fréquence',
    cure_duration:      'Durée',
    cure_start:         'Début',
    cure_end:           'Fin',
    cure_remaining:     'Restant',
    cure_compliance:    'Compliance',
    cure_edit:          '✏️ Modifier',
    cure_stats:         'Statistiques',
    cure_inj_done:      'Injections faites',
    cure_inj_expected:  'Injections attendues',
    cure_inj_missed:    'Manquées',
    cure_current_day:   'Jour actuel',
    cure_new:           'Nouvelle cure',
    cure_start_btn:     'Démarrer la cure',
    cure_save_btn:      'Enregistrer',
    cure_delete_btn:    'Supprimer cette cure',
    cure_empty:         'Aucune cure enregistrée.\nCommencez par ajouter votre premier protocole.',
    cure_add_first:     '+ Nouvelle cure',
    cure_notes:         'Notes (optionnel)',
    cure_notes_ph:      'Objectif, remarques…',
    cure_modal_edit:    'Modifier la cure',
    cure_suggested_site:'Site suggéré',
    cure_change_site:   'Changer →',
    cure_zone:          'Zone :',
    cure_rest_day:      'Jour de repos 😴',
    cure_save_note:     'Enregistrer la note',
    cure_note_ph:       'Note pour ce jour…',
    cure_note_saved:    '✓ Note enregistrée',
    cure_legend_done:   'Fait',
    cure_legend_partial:'Partiel',
    cure_legend_missed: 'Manqué',
    cure_legend_planned:'Prévu',
    cure_legend_rest:   'Repos',
    cure_time_updated:  '✓ Heure mise à jour : ',
    cure_inj_done_msg:  '✓ Injection — ',
    cure_inj_cancelled: 'Injection annulée',
    cure_deleted:       'Cure supprimée',
    cure_updated:       '✓ Cure mise à jour',
    cure_started:       '✓ Cure démarrée !',
    cure_confirm_delete:'Supprimer cette cure ?',
    cure_choose:        'Choisir…',
    cure_my_stock:      '🧪 Mon stock',
    cure_library:       '📚 Bibliothèque',
    days_short:         ['L','M','M','J','V','S','D'],
    months:             ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],

    // ── POIDS ────────────────────────────────────────────────
    weight_title:       'Suivi du poids',
    weight_period_7:    '7j',
    weight_period_30:   '30j',
    weight_period_90:   '3 mois',
    weight_period_all:  'Tout',
    weight_current:     'kg actuel',
    weight_variation:   'variation',
    weight_measures:    'mesures',
    weight_chart_title: 'Évolution',
    weight_add_title:   'Enregistrer mon poids',
    weight_add_btn:     'Ajouter',
    weight_note_ph:     'Note (optionnel)',
    weight_date:        'Date',
    weight_bmi_title:   'IMC',
    weight_history:     'Historique',
    weight_no_data:     'Aucune donnée',
    weight_add_first:   'Ajoutez votre premier poids',
    weight_saved:       '✓ Poids enregistré : ',
    weight_deleted:     'Entrée supprimée',
    weight_modified:    '✓ Poids modifié',
    weight_invalid:     '⚠️ Poids invalide',
    weight_date_req:    '⚠️ Date requise',
    weight_height_title:'📏 Votre taille ?',
    weight_height_sub:  'Nécessaire pour calculer votre IMC correctement.',
    weight_height_ph:   '178',
    weight_height_ok:   'OK',
    weight_height_saved:'✓ Taille enregistrée',
    weight_height_first:'📏 Indiquez votre taille d\'abord',
    weight_height_inv:  '⚠️ Taille invalide',
    weight_bmi_under:   'Insuffisance pondérale',
    weight_bmi_normal:  'Poids normal ✓',
    weight_bmi_over:    'Surpoids',
    weight_bmi_obese:   'Obésité',
    weight_bmi_unit:    'cm · Poids :',
    weight_bmi_height:  'Taille :',

    // ── ALERTES ──────────────────────────────────────────────
    alerts_title:       'Alertes',
    alerts_notif_title: 'Notifications intelligentes',
    alerts_notif_sub:   'Recevez vos rappels d\'injection même quand l\'app est fermée',
    alerts_enable:      'Activer',
    alerts_enabled:     '✓ Activées — Désactiver',
    alerts_blocked:     'Bloquées ⚠️',
    alerts_reminders:   'Rappels d\'injection',
    alerts_no_active:   'Aucune cure active',
    alerts_schedule:    'Planning du jour',
    alerts_auto:        'Alertes actives',
    alerts_custom:      'Mes rappels',
    alerts_add_title:   '+ Nouveau rappel',
    alerts_msg_label:   'Message',
    alerts_msg_ph:      'ex: Prise de sang IGF-1',
    alerts_date:        'Date',
    alerts_time:        'Heure',
    alerts_priority:    'Priorité',
    alerts_prio_normal: 'Normale',
    alerts_prio_high:   'Importante',
    alerts_prio_urgent: 'Urgente',
    alerts_save_btn:    'Enregistrer le rappel',
    alerts_no_auto:     'Aucune alerte automatique 🎉',
    alerts_no_custom:   'Aucun rappel — ajoutez-en un ci-dessus',
    alerts_no_today:    'Aucune injection aujourd\'hui',
    alerts_done:        '✓ Fait',
    alerts_due:         '⏰ À faire',
    alerts_upcoming:    'À venir',
    alerts_added:       '✓ Rappel ajouté !',
    alerts_deleted:     'Rappel supprimé',
    alerts_notif_on:    '🔔 Rappel activé',
    alerts_notif_off:   '🔕 Rappel désactivé',
    alerts_time_saved:  '✓ Heure mise à jour — ',
    alerts_cure_end:    'Fin de cure dans',
    alerts_blood_test:  'Bilan sanguin recommandé',
    alerts_inj_label:   'Injection',
    alerts_inj_day:     'du jour',
    alerts_fill_all:    '⚠️ Remplir tous les champs',
    alerts_notif_unsupported: 'Non supporté sur ce navigateur',
    alerts_notif_activated: '✓ Notifications activées !',
    alerts_notif_refused: 'Notifications refusées — vérifiez les réglages Safari',
    alerts_notif_disabled: '🔕 Notifications désactivées',

    // ── PROFIL ───────────────────────────────────────────────
    profil_title:       'Mon profil',
    profil_plan_free:   'Plan Gratuit',
    profil_plan_prem:   '⭐ Premium',
    profil_info:        'Informations personnelles',
    profil_name:        'Prénom',
    profil_age:         'Âge',
    profil_height:      'Taille',
    profil_goal:        'Objectif',
    profil_stats:       'Mes statistiques',
    profil_subscription:'Abonnement',
    profil_equipment:   'Mon équipement',
    profil_syringes:    '💉 Mes seringues',
    profil_syringes_sub:'Sélectionnez les seringues que vous possédez. Le calculateur s\'adaptera automatiquement.',
    profil_needle_type: '🧪 Type d\'aiguille préféré',
    profil_solvent:     '💧 Solvant de reconstitution préféré',
    profil_settings:    'Paramètres',
    profil_biblio_link: 'Bibliothèque peptides',
    profil_export:      'Exporter mes données',
    profil_export_sub:  'JSON — toutes mes cures et mesures',
    profil_home_link:   "Page d'accueil",
    profil_home_sub:    'Retour à la landing page',
    profil_danger:      'Zone de danger',
    profil_logout:      '🚪 Se déconnecter',
    profil_reset:       '🗑 Supprimer toutes mes données',
    profil_version:     'PeptideScanner v1.0 · Usage éducatif uniquement',
    profil_total_cures: 'Cures totales',
    profil_injections:  'Injections',
    profil_done_cures:  'Cures finies',
    profil_weight_var:  'Variation poids',
    profil_prem_active: '⭐ Premium actif',
    profil_prem_active_sub: 'Vous bénéficiez de toutes les fonctionnalités premium.',
    profil_upgrade:     'Passer Premium',
    profil_upgrade_sub: 'Débloquez le suivi complet, les alertes intelligentes et le conseiller IA.',
    profil_upgrade_btn: '⭐ S\'abonner — 59 € / an',
    profil_feat1:       'Calendrier de cure illimité',
    profil_feat2:       'Suivi du poids + graphiques',
    profil_feat3:       'Alertes & rappels push',
    profil_feat4:       'Conseiller IA spécialisé',
    profil_feat5:       'Cures & calendrier illimités',
    profil_feat6:       'Suivi du poids complet',
    profil_feat7:       'Conseiller IA illimité',
    profil_logout_confirm: 'Se déconnecter ?',
    profil_reset_confirm1: '⚠️ Supprimer TOUTES les données ? Irréversible.',
    profil_reset_confirm2: 'Vraiment supprimer tout ?',
    profil_reset_done:  'Données supprimées',
    profil_export_done: '✓ Données exportées',
    profil_pseudo_title:'Choisissez votre pseudo',
    profil_pseudo_ph:   'Ex: James',
    profil_pseudo_saved:'✓ Pseudo enregistré !',
    profil_updated:     '✓ mis à jour',
    profil_not_filled:  'Non renseigné',
    profil_biblio_count:'52 peptides référencés',
    profil_prem_activated: '⭐ Premium activé !',
    profil_lang:        'Langue',
    profil_lang_sub:    'Français / English',
    needle_4mm:  '4 mm — Très mince (SC abdominal)',
    needle_6mm:  '6 mm — Standard SC',
    needle_8mm:  '8 mm — SC/IM superficiel',
    needle_12mm: '12 mm — IM profond',
    needle_25mm: '25 mm — IM deltoid',
    solvent_bac:   'Eau bactériostatique (BAC) — Recommandé',
    solvent_water: 'Eau stérile pour injection',
    solvent_saline:'Sérum physiologique 0.9%',
    syringe_u30_label: 'U-30',
    syringe_u30_sub:   '0.3 mL — 30 unités · Mini doses',
    syringe_u50_label: 'U-50',
    syringe_u50_sub:   '0.5 mL — 50 unités · Doses moyennes',
    syringe_u100_label:'U-100',
    syringe_u100_sub:  '1.0 mL — 100 unités · Standard',
    syringe_u200_label:'2 mL',
    syringe_u200_sub:  '2.0 mL — Grandes doses / split-dose',

    // ── INVENTAIRE ───────────────────────────────────────────
    inv_title:         'Stock',
    inv_add:           '+ Ajouter un flacon',
    inv_vials:         'flacons',
    inv_low_stock:     'stock bas',
    inv_expired:       'expirés',
    inv_expired_badge: '⚠️ EXPIRÉ',
    inv_low_badge:     '⚠️ STOCK BAS',
    inv_sealed_badge:  '🔒 SCELLÉ',
    inv_modal_add:     'Ajouter un flacon',
    inv_modal_edit:    'Modifier le flacon',
    inv_peptide:       'Peptide',
    inv_peptide_ph:    'Ex: BPC-157, HGH…',
    inv_qty:           'Quantité totale',
    inv_unit:          'Unité',
    inv_dose_inj:      'Dose / injection',
    inv_frequency:     'Fréquence',
    inv_choose_freq:   '-- Choisir --',
    inv_recon_date:    'Date reconstitution',
    inv_status:        'Statut',
    inv_status_active: 'En cours',
    inv_status_sealed: 'Scellé',
    inv_status_done:   'Terminé',
    inv_temp:          '🌡 Temp. conservation',
    inv_temp_ph:       'ex: 2-8°C',
    inv_max_days:      '📅 Durée max (jours)',
    inv_storage_note:  'Note conservation',
    inv_storage_note_ph:'ex: Éviter la lumière',
    inv_note:          'Note (optionnel)',
    inv_note_ph:       'Ex: Lot 2025, cure récupération…',
    inv_save:          'Enregistrer le flacon',
    inv_cancel:        'Annuler',
    inv_inj_left:      'inj. restantes',
    inv_added:         '✓ Flacon ajouté',
    inv_updated:       '✓ Flacon mis à jour',
    inv_deleted:       'Flacon supprimé',
    inv_delete_confirm:'Supprimer ce flacon ?',
    inv_name_required: '⚠️ Nom du peptide requis',
    inv_empty:         'Aucun flacon enregistré.\nAjoutez votre premier flacon.',

    // ── IA ───────────────────────────────────────────────────
    ia_title:          'Conseiller IA',
    ia_online:         '● En ligne · Spécialiste peptides',
    ia_clear:          'Effacer',
    ia_context:        'Contexte :',
    ia_disclaimer:     '⚠️ Usage éducatif — Consultez un professionnel de santé avant tout protocole',
    ia_placeholder:    'Posez votre question sur les peptides…',
    ia_premium_title:  'Fonctionnalité Premium',
    ia_premium_sub:    'Le Conseiller IA est réservé aux membres Premium. Passez au plan Premium pour accéder aux conseils personnalisés.',
    ia_premium_btn:    '⭐ Passer Premium',
    ia_demo:           'Tester en mode démo',
    ia_error:          '⚠️ Erreur de connexion. Réessayez.',
    ia_quota:          'Quota mensuel atteint.',

    // ── CALCULATEUR ──────────────────────────────────────────
    calc_title:        'Calculateur',
    calc_warning:      'Outil d\'information uniquement',
    calc_warning_sub:  'Ce calculateur est un outil d\'information. Vérifiez toujours vos calculs avant toute injection. Consultez un professionnel de santé avant tout protocole. PeptideScanner décline toute responsabilité en cas d\'erreur de dosage.',
    calc_tab_recon:    '🧪 Reconstitution',
    calc_tab_dosage:   '💉 Dosage',
    calc_tab_titration:'📈 Titration',
    calc_tab_guide:    '📋 Guide injection',
    calc_recon_section:'Étape 1 — Calculer la concentration',
    calc_recon_title:  '🧪 Reconstitution du flacon',
    calc_peptide_qty:  'Quantité de peptide dans le flacon',
    calc_bac_volume:   'Volume d\'eau bactériostatique à ajouter',
    calc_recon_result: '✓ Résultat de la reconstitution',
    calc_dosage_section:'Calculer précisément votre dose',
    calc_dosage_title: '💉 Calculateur de dose précise',
    calc_dosage_sub:   'Entrez votre concentration (calculée dans l\'onglet Reconstitution) et la dose souhaitée.',
    calc_unit:         'Unité du peptide',
    calc_concentration:'Concentration du flacon reconstitué',
    calc_desired_dose: 'Dose souhaitée',
    calc_syringe:      'Type de seringue',
    calc_auto_syringe: '✓ Auto-sélectionnée',
    calc_dosage_result:'✓ Résultat du dosage',
    calc_titration_section:'Plan de titration progressive',
    calc_guide_section:'Guide d\'injection pas à pas',
    calc_guide_recon:  'Étapes de reconstitution',
    calc_guide_sc:     'Guide d\'injection sous-cutanée',
    calc_guide_warning_title: 'Avertissement médical',
    calc_guide_warning_sub: 'Ce guide est à titre éducatif uniquement. Toute injection doit être validée par un professionnel de santé. En cas de doute, ne pas procéder. PeptideScanner n\'est pas responsable des erreurs de manipulation ou de dosage.',
    calc_high_dose_title: 'Dose élevée détectée',
    calc_high_dose_confirm: 'J\'ai vérifié — continuer quand même',
    calc_high_dose_cancel:  '← Recalculer ma dose',
    calc_dose_table_dose: 'Dose',
  },

  // ══════════════════════════════════════════════════════════
  en: {
    // ── NAV ──────────────────────────────────────────────────
    nav_home:       'Home',
    nav_cure:       'Cycle',
    nav_calc:       'Calc',
    nav_stock:      'Stock',
    nav_alerts:     'Alerts',
    nav_profile:    'Profile',
    nav_biblio:     'Library',
    nav_weight:     'Weight',
    nav_ia:         'AI',
    nav_analyse:    'Analytics',

    // ── COMMON ───────────────────────────────────────────────
    save:           'Save',
    cancel:         'Cancel',
    delete:         'Delete',
    edit:           'Edit',
    add:            'Add',
    confirm:        'Confirm',
    close:          'Close',
    loading:        'Loading…',
    error:          'Error',
    success:        'Success',
    optional:       'optional',
    all:            'All',
    none:           'None',
    days:           'days',
    day:            'day',
    today:          'Today',
    week:           'week',
    month:          'month',
    yes:            'Yes',
    no:             'No',
    back:           'Back',
    next:           'Next',
    see_all:        'See all →',
    details:        'Detail →',
    no_data:        'No data',

    // ── DISCLAIMER ───────────────────────────────────────────
    disclaimer_short: 'Educational use only — Research peptides not approved for human use. Consult a healthcare professional. PeptideScanner disclaims all liability.',
    disclaimer_icon:  '⚠️',

    // ── DASHBOARD ────────────────────────────────────────────
    dash_greeting:        'Hello 👋',
    dash_active_cure:     'Active cycle',
    dash_protocol:        'Current protocol',
    dash_no_cure:         'No active cycle',
    dash_no_cure_sub:     'Tap "+ New cycle" to get started',
    dash_day_label:       '/ days',
    dash_calendar:        '📅 Calendar',
    dash_new_cure:        '＋ New cycle',
    dash_summary:         'Summary',
    dash_weight_title:    'Weight progress',
    dash_today_section:   'Today',
    dash_calendar_link:   'Calendar →',
    dash_alerts_section:  'Recent alerts',
    dash_alerts_all:      'All →',
    dash_no_alerts:       'No active alerts 🎉',
    dash_weight_go:       'Weight →',
    dash_inj_done:        'Injections done',
    dash_days_left:       'Days remaining',
    dash_end_date:        'Estimated end',
    dash_compliance:      'Compliance',
    dash_cures_done:      'Completed cycles',
    dash_total_inj:       'Total injections',
    dash_current_weight:  'Current weight',
    dash_since_start:     'since start',
    dash_first_measure:   'First measure',
    dash_no_weight_data:  'No data — Add your weight',
    dash_score_label:     'doses done',
    dash_score_done:      '✅ Complete',
    dash_today_program:   "Today's schedule",
    dash_no_injection:    'No injection scheduled today.',
    dash_injection_day:   'Daily injection',
    dash_injection_num:   'Injection',
    dash_confirm_inj:     'Confirm injection',
    dash_check_time:      'Check the time before confirming',
    dash_inj_time:        '⏰ Injection time',
    dash_validate:        '✓ Confirm injection',
    dash_new_cure_title:  'New cycle',
    dash_peptide:         'Peptide',
    dash_choose_peptide:  'Choose a peptide…',
    dash_dosage:          'Dosage',
    dash_admin:           'Route',
    dash_start_date:      'Start date',
    dash_duration:        'Duration (days)',
    dash_frequency:       'Injection frequency',
    dash_start_cure:      'Start cycle',
    dash_cure_ended:      'Cycle ends in',
    dash_days_suffix:     'd',
    dash_inj_cancelled:   'Injection cancelled',
    dash_inj_saved:       '— saved!',
    freq_1x:    '1× per day',
    freq_2x:    '2× per day',
    freq_3x:    '3× per day',
    freq_1_2d:  'Every 2 days',
    freq_2x_w:  '2× per week',
    freq_1x_w:  '1× per week',
    admin_sc:   'SC',
    admin_im:   'IM',
    admin_oral: 'Oral',
    admin_nasal:'Nasal',
    admin_iv:   'IV',

    // ── CURE ─────────────────────────────────────────────────
    cure_title:         'Cycle calendar',
    cure_status_active: 'Active',
    cure_status_ended:  'Completed',
    cure_status_future: 'Upcoming',
    cure_dosage:        'Dosage',
    cure_frequency:     'Frequency',
    cure_duration:      'Duration',
    cure_start:         'Start',
    cure_end:           'End',
    cure_remaining:     'Remaining',
    cure_compliance:    'Compliance',
    cure_edit:          '✏️ Edit',
    cure_stats:         'Statistics',
    cure_inj_done:      'Injections done',
    cure_inj_expected:  'Expected injections',
    cure_inj_missed:    'Missed',
    cure_current_day:   'Current day',
    cure_new:           'New cycle',
    cure_start_btn:     'Start cycle',
    cure_save_btn:      'Save',
    cure_delete_btn:    'Delete this cycle',
    cure_empty:         'No cycle recorded.\nStart by adding your first protocol.',
    cure_add_first:     '+ New cycle',
    cure_notes:         'Notes (optional)',
    cure_notes_ph:      'Goal, remarks…',
    cure_modal_edit:    'Edit cycle',
    cure_suggested_site:'Suggested site',
    cure_change_site:   'Change →',
    cure_zone:          'Zone:',
    cure_rest_day:      'Rest day 😴',
    cure_save_note:     'Save note',
    cure_note_ph:       'Note for this day…',
    cure_note_saved:    '✓ Note saved',
    cure_legend_done:   'Done',
    cure_legend_partial:'Partial',
    cure_legend_missed: 'Missed',
    cure_legend_planned:'Planned',
    cure_legend_rest:   'Rest',
    cure_time_updated:  '✓ Time updated: ',
    cure_inj_done_msg:  '✓ Injection — ',
    cure_inj_cancelled: 'Injection cancelled',
    cure_deleted:       'Cycle deleted',
    cure_updated:       '✓ Cycle updated',
    cure_started:       '✓ Cycle started!',
    cure_confirm_delete:'Delete this cycle?',
    cure_choose:        'Choose…',
    cure_my_stock:      '🧪 My stock',
    cure_library:       '📚 Library',
    days_short:         ['M','T','W','T','F','S','S'],
    months:             ['January','February','March','April','May','June','July','August','September','October','November','December'],

    // ── POIDS ────────────────────────────────────────────────
    weight_title:       'Weight tracking',
    weight_period_7:    '7d',
    weight_period_30:   '30d',
    weight_period_90:   '3 months',
    weight_period_all:  'All',
    weight_current:     'current kg',
    weight_variation:   'change',
    weight_measures:    'entries',
    weight_chart_title: 'Progress',
    weight_add_title:   'Log my weight',
    weight_add_btn:     'Add',
    weight_note_ph:     'Note (optional)',
    weight_date:        'Date',
    weight_bmi_title:   'BMI',
    weight_history:     'History',
    weight_no_data:     'No data',
    weight_add_first:   'Add your first weight',
    weight_saved:       '✓ Weight saved: ',
    weight_deleted:     'Entry deleted',
    weight_modified:    '✓ Weight updated',
    weight_invalid:     '⚠️ Invalid weight',
    weight_date_req:    '⚠️ Date required',
    weight_height_title:'📏 Your height?',
    weight_height_sub:  'Required to calculate your BMI correctly.',
    weight_height_ph:   '178',
    weight_height_ok:   'OK',
    weight_height_saved:'✓ Height saved',
    weight_height_first:'📏 Enter your height first',
    weight_height_inv:  '⚠️ Invalid height',
    weight_bmi_under:   'Underweight',
    weight_bmi_normal:  'Normal weight ✓',
    weight_bmi_over:    'Overweight',
    weight_bmi_obese:   'Obesity',
    weight_bmi_unit:    'cm · Weight:',
    weight_bmi_height:  'Height:',

    // ── ALERTES ──────────────────────────────────────────────
    alerts_title:       'Alerts',
    alerts_notif_title: 'Smart notifications',
    alerts_notif_sub:   'Receive injection reminders even when the app is closed',
    alerts_enable:      'Enable',
    alerts_enabled:     '✓ Enabled — Disable',
    alerts_blocked:     'Blocked ⚠️',
    alerts_reminders:   'Injection reminders',
    alerts_no_active:   'No active cycle',
    alerts_schedule:    "Today's schedule",
    alerts_auto:        'Active alerts',
    alerts_custom:      'My reminders',
    alerts_add_title:   '+ New reminder',
    alerts_msg_label:   'Message',
    alerts_msg_ph:      'e.g.: IGF-1 blood test',
    alerts_date:        'Date',
    alerts_time:        'Time',
    alerts_priority:    'Priority',
    alerts_prio_normal: 'Normal',
    alerts_prio_high:   'Important',
    alerts_prio_urgent: 'Urgent',
    alerts_save_btn:    'Save reminder',
    alerts_no_auto:     'No automatic alerts 🎉',
    alerts_no_custom:   'No reminders — add one above',
    alerts_no_today:    'No injection today',
    alerts_done:        '✓ Done',
    alerts_due:         '⏰ Due',
    alerts_upcoming:    'Upcoming',
    alerts_added:       '✓ Reminder added!',
    alerts_deleted:     'Reminder deleted',
    alerts_notif_on:    '🔔 Reminder enabled',
    alerts_notif_off:   '🔕 Reminder disabled',
    alerts_time_saved:  '✓ Time updated — ',
    alerts_cure_end:    'Cycle ends in',
    alerts_blood_test:  'Blood test recommended',
    alerts_inj_label:   'Injection',
    alerts_inj_day:     'of the day',
    alerts_fill_all:    '⚠️ Fill all fields',
    alerts_notif_unsupported: 'Not supported on this browser',
    alerts_notif_activated: '✓ Notifications enabled!',
    alerts_notif_refused: 'Notifications denied — check Safari settings',
    alerts_notif_disabled: '🔕 Notifications disabled',

    // ── PROFIL ───────────────────────────────────────────────
    profil_title:       'My profile',
    profil_plan_free:   'Free plan',
    profil_plan_prem:   '⭐ Premium',
    profil_info:        'Personal information',
    profil_name:        'First name',
    profil_age:         'Age',
    profil_height:      'Height',
    profil_goal:        'Goal',
    profil_stats:       'My statistics',
    profil_subscription:'Subscription',
    profil_equipment:   'My equipment',
    profil_syringes:    '💉 My syringes',
    profil_syringes_sub:'Select the syringes you own. The calculator will adapt automatically.',
    profil_needle_type: '🧪 Preferred needle type',
    profil_solvent:     '💧 Preferred reconstitution solvent',
    profil_settings:    'Settings',
    profil_biblio_link: 'Peptide library',
    profil_export:      'Export my data',
    profil_export_sub:  'JSON — all my cycles and measurements',
    profil_home_link:   'Home page',
    profil_home_sub:    'Back to landing page',
    profil_danger:      'Danger zone',
    profil_logout:      '🚪 Sign out',
    profil_reset:       '🗑 Delete all my data',
    profil_version:     'PeptideScanner v1.0 · Educational use only',
    profil_total_cures: 'Total cycles',
    profil_injections:  'Injections',
    profil_done_cures:  'Finished cycles',
    profil_weight_var:  'Weight change',
    profil_prem_active: '⭐ Premium active',
    profil_prem_active_sub: 'You have access to all premium features.',
    profil_upgrade:     'Go Premium',
    profil_upgrade_sub: 'Unlock full tracking, smart alerts and AI advisor.',
    profil_upgrade_btn: '⭐ Subscribe — €59 / year',
    profil_feat1:       'Unlimited cycle calendar',
    profil_feat2:       'Weight tracking + charts',
    profil_feat3:       'Alerts & push reminders',
    profil_feat4:       'Specialized AI advisor',
    profil_feat5:       'Unlimited cycles & calendar',
    profil_feat6:       'Full weight tracking',
    profil_feat7:       'Unlimited AI advisor',
    profil_logout_confirm: 'Sign out?',
    profil_reset_confirm1: '⚠️ Delete ALL data? Irreversible.',
    profil_reset_confirm2: 'Really delete everything?',
    profil_reset_done:  'Data deleted',
    profil_export_done: '✓ Data exported',
    profil_pseudo_title:'Choose your username',
    profil_pseudo_ph:   'e.g.: James',
    profil_pseudo_saved:'✓ Username saved!',
    profil_updated:     '✓ updated',
    profil_not_filled:  'Not set',
    profil_biblio_count:'52 peptides referenced',
    profil_prem_activated: '⭐ Premium activated!',
    profil_lang:        'Language',
    profil_lang_sub:    'Français / English',
    needle_4mm:  '4 mm — Very thin (SC abdominal)',
    needle_6mm:  '6 mm — Standard SC',
    needle_8mm:  '8 mm — Shallow SC/IM',
    needle_12mm: '12 mm — Deep IM',
    needle_25mm: '25 mm — IM deltoid',
    solvent_bac:   'Bacteriostatic water (BAC) — Recommended',
    solvent_water: 'Sterile water for injection',
    solvent_saline:'Normal saline 0.9%',
    syringe_u30_label: 'U-30',
    syringe_u30_sub:   '0.3 mL — 30 units · Mini doses',
    syringe_u50_label: 'U-50',
    syringe_u50_sub:   '0.5 mL — 50 units · Medium doses',
    syringe_u100_label:'U-100',
    syringe_u100_sub:  '1.0 mL — 100 units · Standard',
    syringe_u200_label:'2 mL',
    syringe_u200_sub:  '2.0 mL — Large doses / split-dose',

    // ── INVENTAIRE ───────────────────────────────────────────
    inv_title:         'Stock',
    inv_add:           '+ Add vial',
    inv_vials:         'vials',
    inv_low_stock:     'low stock',
    inv_expired:       'expired',
    inv_expired_badge: '⚠️ EXPIRED',
    inv_low_badge:     '⚠️ LOW STOCK',
    inv_sealed_badge:  '🔒 SEALED',
    inv_modal_add:     'Add a vial',
    inv_modal_edit:    'Edit vial',
    inv_peptide:       'Peptide',
    inv_peptide_ph:    'e.g.: BPC-157, HGH…',
    inv_qty:           'Total quantity',
    inv_unit:          'Unit',
    inv_dose_inj:      'Dose / injection',
    inv_frequency:     'Frequency',
    inv_choose_freq:   '-- Choose --',
    inv_recon_date:    'Reconstitution date',
    inv_status:        'Status',
    inv_status_active: 'Active',
    inv_status_sealed: 'Sealed',
    inv_status_done:   'Finished',
    inv_temp:          '🌡 Storage temp.',
    inv_temp_ph:       'e.g.: 2-8°C',
    inv_max_days:      '📅 Max duration (days)',
    inv_storage_note:  'Storage note',
    inv_storage_note_ph:'e.g.: Keep away from light',
    inv_note:          'Note (optional)',
    inv_note_ph:       'e.g.: Lot 2025, recovery cycle…',
    inv_save:          'Save vial',
    inv_cancel:        'Cancel',
    inv_inj_left:      'injections left',
    inv_added:         '✓ Vial added',
    inv_updated:       '✓ Vial updated',
    inv_deleted:       'Vial deleted',
    inv_delete_confirm:'Delete this vial?',
    inv_name_required: '⚠️ Peptide name required',
    inv_empty:         'No vials recorded.\nAdd your first vial.',

    // ── IA ───────────────────────────────────────────────────
    ia_title:          'AI Advisor',
    ia_online:         '● Online · Peptide specialist',
    ia_clear:          'Clear',
    ia_context:        'Context:',
    ia_disclaimer:     '⚠️ Educational use — Consult a healthcare professional before any protocol',
    ia_placeholder:    'Ask your peptide question…',
    ia_premium_title:  'Premium feature',
    ia_premium_sub:    'The AI Advisor is reserved for Premium members. Upgrade to access personalized advice.',
    ia_premium_btn:    '⭐ Go Premium',
    ia_demo:           'Try demo mode',
    ia_error:          '⚠️ Connection error. Please retry.',
    ia_quota:          'Monthly quota reached.',

    // ── CALCULATEUR ──────────────────────────────────────────
    calc_title:        'Calculator',
    calc_warning:      'Information tool only',
    calc_warning_sub:  'This calculator is an information tool. Always verify your calculations before any injection. Consult a healthcare professional before any protocol. PeptideScanner disclaims all liability for dosage errors.',
    calc_tab_recon:    '🧪 Reconstitution',
    calc_tab_dosage:   '💉 Dosage',
    calc_tab_titration:'📈 Titration',
    calc_tab_guide:    '📋 Injection guide',
    calc_recon_section:'Step 1 — Calculate concentration',
    calc_recon_title:  '🧪 Vial reconstitution',
    calc_peptide_qty:  'Peptide quantity in vial',
    calc_bac_volume:   'Bacteriostatic water volume to add',
    calc_recon_result: '✓ Reconstitution result',
    calc_dosage_section:'Calculate your precise dose',
    calc_dosage_title: '💉 Precise dose calculator',
    calc_dosage_sub:   'Enter your concentration (calculated in the Reconstitution tab) and desired dose.',
    calc_unit:         'Peptide unit',
    calc_concentration:'Reconstituted vial concentration',
    calc_desired_dose: 'Desired dose',
    calc_syringe:      'Syringe type',
    calc_auto_syringe: '✓ Auto-selected',
    calc_dosage_result:'✓ Dosage result',
    calc_titration_section:'Progressive titration plan',
    calc_guide_section:'Step-by-step injection guide',
    calc_guide_recon:  'Reconstitution steps',
    calc_guide_sc:     'Subcutaneous injection guide',
    calc_guide_warning_title: 'Medical disclaimer',
    calc_guide_warning_sub: 'This guide is for educational purposes only. Any injection must be validated by a healthcare professional. If in doubt, do not proceed. PeptideScanner is not responsible for handling or dosage errors.',
    calc_high_dose_title: 'High dose detected',
    calc_high_dose_confirm: 'I have verified — proceed anyway',
    calc_high_dose_cancel:  '← Recalculate my dose',
    calc_dose_table_dose: 'Dose',
  }
};

// ══════════════════════════════════════════════════════════════
// MOTEUR DE TRADUCTION
// ══════════════════════════════════════════════════════════════

/**
 * Retourne la langue active ('fr' ou 'en')
 */
window.PS_getLang = function() {
  return localStorage.getItem('ps_lang') || 'fr';
};

/**
 * Retourne une chaîne traduite
 * @param {string} key
 * @returns {string}
 */
window.t = function(key) {
  const lang = window.PS_getLang();
  return (window.PS_LANG[lang] && window.PS_LANG[lang][key]) ||
         (window.PS_LANG['fr'][key]) ||
         key;
};

/**
 * Change la langue, sauvegarde en localStorage ET Supabase si sb + userId disponibles
 * @param {string} lang - 'fr' | 'en'
 */
window.PS_setLang = async function(lang) {
  if (lang !== 'fr' && lang !== 'en') return;
  localStorage.setItem('ps_lang', lang);
  // Persister dans Supabase si disponible
  if (window._ps_sb && window._ps_userId) {
    try {
      await window._ps_sb.from('profiles').update({ lang }).eq('id', window._ps_userId);
    } catch(e) { /* silencieux */ }
  }
  // Recharger la page pour appliquer (le plus simple et fiable)
  location.reload();
};

/**
 * Charge la langue depuis Supabase (profile.lang) et met à jour localStorage
 * À appeler après auth, en passant sb et userId
 */
window.PS_loadLangFromProfile = function(sb, userId, profileLang) {
  window._ps_sb     = sb;
  window._ps_userId = userId;
  if (profileLang && (profileLang === 'fr' || profileLang === 'en')) {
    const local = localStorage.getItem('ps_lang');
    // Supabase a priorité si pas encore de préférence locale
    if (!local) localStorage.setItem('ps_lang', profileLang);
  }
};

/**
 * Injecte le bouton toggle FR|EN dans un élément topbar
 * @param {string} containerId - id de l'élément où insérer le toggle
 */
window.PS_injectLangToggle = function(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;
  const current = window.PS_getLang();
  const btn = document.createElement('button');
  btn.id = 'langToggleBtn';
  btn.innerHTML = current === 'fr' ? '🇬🇧 EN' : '🇫🇷 FR';
  btn.style.cssText = [
    'background:transparent',
    'border:1px solid var(--border)',
    'color:var(--muted)',
    'border-radius:8px',
    'padding:5px 10px',
    'font-family:inherit',
    'font-size:.72rem',
    'font-weight:700',
    'cursor:pointer',
    'transition:all .2s',
    'white-space:nowrap',
    'flex-shrink:0',
  ].join(';');
  btn.onmouseover = () => { btn.style.borderColor = 'var(--accent)'; btn.style.color = 'var(--accent)'; };
  btn.onmouseout  = () => { btn.style.borderColor = 'var(--border)'; btn.style.color = 'var(--muted)';  };
  btn.onclick = () => window.PS_setLang(current === 'fr' ? 'en' : 'fr');
  container.appendChild(btn);
};

/**
 * Applique toutes les traductions data-i18n sur la page
 * Appelée une fois au chargement, après avoir défini la langue
 */
window.PS_applyI18n = function() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = window.t(key);
    if (val) el.textContent = val;
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    const val = window.t(key);
    if (val) el.placeholder = val;
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    const val = window.t(key);
    if (val) el.title = val;
  });
};
