// ============================================================
// lang.js — Système de traduction PeptideScanner
// FR + EN · Objet global window.PS_LANG
// Usage : <script src="/lang.js"></script>
// ============================================================

window.PS_LANG = {

  fr: {
    // ── NAV ──────────────────────────────────────────────────
    nav_home:       'Accueil',
    nav_cure:       'Cure',
    nav_calc:       'Calcul',
    nav_stock:      'Stock',
    nav_alerts:     'Alertes',
    nav_profile:    'Profil',
    nav_biblio:     'Biblio',
    nav_weight:     'Poids',
    nav_ia:         'IA',
    nav_analyse:    'Analyse',

    // ── COMMON ───────────────────────────────────────────────
    save:           'Enregistrer',
    cancel:         'Annuler',
    delete:         'Supprimer',
    edit:           'Modifier',
    add:            'Ajouter',
    confirm:        'Confirmer',
    close:          'Fermer',
    loading:        'Chargement…',
    error:          'Erreur',
    success:        'Succès',
    optional:       'optionnel',
    all:            'Tout',
    none:           'Aucun',
    days:           'jours',
    day:            'jour',
    today:          "Aujourd'hui",
    week:           'semaine',
    month:          'mois',
    yes:            'Oui',
    no:             'Non',
    back:           'Retour',
    next:           'Suivant',
    see_all:        'Voir tout →',
    details:        'Détail →',
    no_data:        'Aucune donnée',

    // ── DISCLAIMER ───────────────────────────────────────────
    disclaimer_title: 'Usage éducatif uniquement',
    disclaimer_short: 'Peptides de recherche non approuvés à usage humain. Consultez un professionnel de santé. PeptideScanner décline toute responsabilité.',
    disclaimer_icon:  '⚠️',

    // ── DASHBOARD ────────────────────────────────────────────
    dash_greeting:        'Bonjour 👋',
    dash_active_cure:     'Cure active',
    dash_protocol:        'Protocole en cours',
    dash_no_cure:         'Aucune cure active',
    dash_no_cure_sub:     'Appuyez sur "+ Nouvelle cure" pour commencer',
    dash_day_label:       '/ jours',
    dash_calendar:        '📅 Calendrier',
    dash_new_cure:        '＋ Nouvelle cure',
    dash_summary:         'Résumé',
    dash_weight_title:    'Évolution du poids',
    dash_today_section:   "Aujourd'hui",
    dash_calendar_link:   'Calendrier →',
    dash_alerts_section:  'Alertes récentes',
    dash_alerts_all:      'Toutes →',
    dash_no_alerts:       'Aucune alerte active 🎉',
    dash_weight_go:       'Poids →',
    dash_inj_done:        'Injections faites',
    dash_days_left:       'Jours restants',
    dash_end_date:        'Fin estimée',
    dash_compliance:      'Compliance',
    dash_cures_done:      'Cures complétées',
    dash_total_inj:       'Injections totales',
    dash_current_weight:  'Poids actuel',
    dash_since_start:     'depuis le début',
    dash_first_measure:   'Première mesure',
    dash_no_weight_data:  'Aucune donnée — Ajouter votre poids',
    dash_score_label:     'doses faites',
    dash_score_done:      '✅ Complété',
    dash_today_program:   'Programme du jour',
    dash_no_injection:    'Aucune injection prévue aujourd\'hui.',
    dash_injection_day:   'Injection du jour',
    dash_injection_num:   'Injection',
    dash_confirm_inj:     'Confirmer l\'injection',
    dash_check_time:      'Vérifiez l\'heure avant de valider',
    dash_inj_time:        '⏰ Heure d\'injection',
    dash_validate:        '✓ Valider l\'injection',
    dash_new_cure_title:  'Nouvelle cure',
    dash_peptide:         'Peptide',
    dash_choose_peptide:  'Choisir un peptide…',
    dash_dosage:          'Dosage',
    dash_admin:           'Administration',
    dash_start_date:      'Date de début',
    dash_duration:        'Durée (jours)',
    dash_frequency:       'Fréquence d\'injection',
    dash_start_cure:      'Démarrer la cure',
    dash_cure_ended:      'Fin de cure dans',
    dash_days_suffix:     'j',
    dash_inj_cancelled:   'Injection annulée',
    dash_inj_saved:       '— enregistré !',
    freq_1x:    '1× par jour',
    freq_2x:    '2× par jour',
    freq_3x:    '3× par jour',
    freq_1_2d:  '1× tous les 2 jours',
    freq_2x_w:  '2× par semaine',
    freq_1x_w:  '1× par semaine',
    admin_sc:   'SC',
    admin_im:   'IM',
    admin_oral: 'Oral',
    admin_nasal:'Nasal',
    admin_iv:   'IV',

    // ── CURE ─────────────────────────────────────────────────
    cure_title:         'Calendrier de cure',
    cure_status_active: 'En cours',
    cure_status_ended:  'Terminée',
    cure_status_future: 'À venir',
    cure_dosage:        'Dosage',
    cure_frequency:     'Fréquence',
    cure_duration:      'Durée',
    cure_start:         'Début',
    cure_end:           'Fin',
    cure_remaining:     'Restant',
    cure_compliance:    'Compliance',
    cure_edit:          '✏️ Modifier',
    cure_stats:         'Statistiques',
    cure_inj_done:      'Injections faites',
    cure_inj_expected:  'Injections attendues',
    cure_inj_missed:    'Manquées',
    cure_current_day:   'Jour actuel',
    cure_new:           'Nouvelle cure',
    cure_start_btn:     'Démarrer la cure',
    cure_save_btn:      'Enregistrer',
    cure_delete_btn:    'Supprimer cette cure',
    cure_empty:         'Aucune cure enregistrée.\nCommencez par ajouter votre premier protocole.',
    cure_add_first:     '+ Nouvelle cure',
    cure_notes:         'Notes (optionnel)',
    cure_notes_ph:      'Objectif, remarques…',
    cure_modal_edit:    'Modifier la cure',
    cure_suggested_site:'Site suggéré',
    cure_change_site:   'Changer →',
    cure_zone:          'Zone :',
    cure_rest_day:      'Jour de repos 😴',
    cure_save_note:     'Enregistrer la note',
    cure_note_ph:       'Note pour ce jour…',
    cure_note_saved:    '✓ Note enregistrée',
    cure_legend_done:   'Fait',
    cure_legend_partial:'Partiel',
    cure_legend_missed: 'Manqué',
    cure_legend_planned:'Prévu',
    cure_legend_rest:   'Repos',
    cure_time_updated:  '✓ Heure mise à jour : ',
    cure_inj_done_msg:  '✓ Injection — ',
    cure_inj_cancelled: 'Injection annulée',
    cure_deleted:       'Cure supprimée',
    cure_updated:       '✓ Cure mise à jour',
    cure_started:       '✓ Cure démarrée !',
    cure_confirm_delete:'Supprimer cette cure ?',
    cure_choose:        'Choisir…',
    // ── TITRATION ─────────────────────────────────────────────
    titration_title:      'Titration progressive',
    titration_sub:        'Paliers de dose progressifs (max 4)',
    titration_add_palier: 'Ajouter un palier',
    titration_palier:     'Palier',
    titration_duration:   'Durée (jours)',
    titration_info:       'La dose principale sera ignorée — chaque palier définit sa propre dose.',
    cure_my_stock:      '🧪 Mon stock',
    cure_library:       '📚 Bibliothèque',
    days_short:         ['L','M','M','J','V','S','D'],
    months:             ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],

    // ── POIDS ────────────────────────────────────────────────
    weight_title:       'Suivi du poids',
    weight_period_7:    '7j',
    weight_period_30:   '30j',
    weight_period_90:   '3 mois',
    weight_period_all:  'Tout',
    weight_current:     'kg actuel',
    weight_variation:   'variation',
    weight_measures:    'mesures',
    weight_chart_title: 'Évolution',
    weight_add_title:   'Enregistrer mon poids',
    weight_add_btn:     'Ajouter',
    weight_note_ph:     'Note (optionnel)',
    weight_date:        'Date',
    weight_bmi_title:   'IMC',
    weight_history:     'Historique',
    weight_no_data:     'Aucune donnée',
    weight_add_first:   'Ajoutez votre premier poids',
    weight_saved:       '✓ Poids enregistré : ',
    weight_deleted:     'Entrée supprimée',
    weight_modified:    '✓ Poids modifié',
    weight_invalid:     '⚠️ Poids invalide',
    weight_date_req:    '⚠️ Date requise',
    weight_height_title:'📏 Votre taille ?',
    weight_height_sub:  'Nécessaire pour calculer votre IMC correctement.',
    weight_height_ph:   '178',
    weight_height_ok:   'OK',
    weight_height_saved:'✓ Taille enregistrée',
    weight_height_first:'📏 Indiquez votre taille d\'abord',
    weight_height_inv:  '⚠️ Taille invalide',
    weight_bmi_under:   'Insuffisance pondérale',
    weight_bmi_normal:  'Poids normal ✓',
    weight_bmi_over:    'Surpoids',
    weight_bmi_obese:   'Obésité',
    weight_bmi_unit:    'cm · Poids :',
    weight_bmi_height:  'Taille :',

    // ── ALERTES ──────────────────────────────────────────────
    alerts_title:       'Alertes',
    alerts_notif_title: 'Notifications intelligentes',
    alerts_notif_sub:   'Recevez vos rappels d\'injection même quand l\'app est fermée',
    alerts_enable:      'Activer',
    alerts_enabled:     '✓ Activées — Désactiver',
    alerts_blocked:     'Bloquées ⚠️',
    alerts_reminders:   'Rappels d\'injection',
    alerts_no_active:   'Aucune cure active',
    alerts_schedule:    'Planning du jour',
    alerts_auto:        'Alertes actives',
    alerts_custom:      'Mes rappels',
    alerts_add_title:   '+ Nouveau rappel',
    alerts_msg_label:   'Message',
    alerts_msg_ph:      'ex: Prise de sang IGF-1',
    alerts_date:        'Date',
    alerts_time:        'Heure',
    alerts_priority:    'Priorité',
    alerts_prio_normal: 'Normale',
    alerts_prio_high:   'Importante',
    alerts_prio_urgent: 'Urgente',
    alerts_save_btn:    'Enregistrer le rappel',
    alerts_no_auto:     'Aucune alerte automatique 🎉',
    alerts_no_custom:   'Aucun rappel — ajoutez-en un ci-dessus',
    alerts_no_today:    'Aucune injection aujourd\'hui',
    alerts_done:        '✓ Fait',
    alerts_due:         '⏰ À faire',
    alerts_upcoming:    'À venir',
    alerts_added:       '✓ Rappel ajouté !',
    alerts_deleted:     'Rappel supprimé',
    alerts_notif_on:    '🔔 Rappel activé',
    alerts_notif_off:   '🔕 Rappel désactivé',
    alerts_time_saved:  '✓ Heure mise à jour — ',
    alerts_cure_end:    'Fin de cure dans',
    alerts_blood_test:  'Bilan sanguin recommandé',
    alerts_inj_label:   'Injection',
    alerts_inj_day:     'du jour',
    alerts_fill_all:    '⚠️ Remplir tous les champs',
    alerts_notif_unsupported: 'Non supporté sur ce navigateur',
    alerts_notif_activated: '✓ Notifications activées !',
    alerts_notif_refused: 'Notifications refusées — vérifiez les réglages Safari',
    alerts_notif_disabled: '🔕 Notifications désactivées',
    alerts_blocked_help:   '⚙️ Autorisez les notifications dans Réglages Safari → Sites web → Notifications',

    // ── PROFIL ───────────────────────────────────────────────
    profil_title:       'Mon profil',
    profil_plan_free:   'Plan Gratuit',
    profil_plan_prem:   '⭐ Premium',
    profil_info:        'Informations personnelles',
    profil_name:        'Prénom',
    profil_age:         'Âge',
    profil_height:      'Taille',
    profil_goal:        'Objectif',
    profil_stats:       'Mes statistiques',
    profil_subscription:'Abonnement',
    profil_equipment:   'Mon équipement',
    profil_syringes:    '💉 Mes seringues',
    profil_syringes_sub:'Sélectionnez les seringues que vous possédez. Le calculateur s\'adaptera automatiquement.',
    profil_needle_type: '🧪 Type d\'aiguille préféré',
    profil_solvent:     '💧 Solvant de reconstitution préféré',
    profil_settings:    'Paramètres',
    profil_biblio_link: 'Bibliothèque peptides',
    profil_export:      'Exporter mes données',
    profil_export_sub:  'JSON — toutes mes cures et mesures',
    profil_home_link:   "Page d'accueil",
    profil_home_sub:    'Retour à la landing page',
    profil_danger:      'Zone de danger',
    profil_logout:      '🚪 Se déconnecter',
    profil_reset:       '🗑 Supprimer toutes mes données',
    profil_version:     'PeptideScanner v1.0 · Usage éducatif uniquement',
    profil_total_cures: 'Cures totales',
    profil_injections:  'Injections',
    profil_done_cures:  'Cures finies',
    profil_weight_var:  'Variation poids',
    profil_prem_active: '⭐ Premium actif',
    profil_prem_active_sub: 'Vous bénéficiez de toutes les fonctionnalités premium.',
    profil_upgrade:     'Passer Premium',
    profil_upgrade_sub: 'Débloquez le suivi complet, les alertes intelligentes et le conseiller IA.',
    profil_upgrade_btn: '⭐ S\'abonner — 59 € / an',
    profil_feat1:       'Calendrier de cure illimité',
    profil_feat2:       'Suivi du poids + graphiques',
    profil_feat3:       'Alertes & rappels push',
    profil_feat4:       'Conseiller IA spécialisé',
    profil_feat5:       'Cures & calendrier illimités',
    profil_feat6:       'Suivi du poids complet',
    profil_feat7:       'Conseiller IA illimité',
    profil_logout_confirm: 'Se déconnecter ?',
    profil_reset_confirm1: '⚠️ Supprimer TOUTES les données ? Irréversible.',
    profil_reset_confirm2: 'Vraiment supprimer tout ?',
    profil_reset_done:  'Données supprimées',
    profil_export_done: '✓ Données exportées',
    profil_pseudo_title:'Choisissez votre pseudo',
    profil_pseudo_ph:   'Ex: James',
    profil_pseudo_saved:'✓ Pseudo enregistré !',
    profil_updated:     '✓ mis à jour',
    profil_not_filled:  'Non renseigné',
    profil_biblio_count:'52 peptides référencés',
    profil_prem_activated: '⭐ Premium activé !',
    profil_lang:        'Langue',
    profil_lang_sub:    'Français / English',
    needle_4mm:  '4 mm — Très mince (SC abdominal)',
    needle_6mm:  '6 mm — Standard SC',
    needle_8mm:  '8 mm — SC/IM superficiel',
    needle_12mm: '12 mm — IM profond',
    needle_25mm: '25 mm — IM deltoid',
    solvent_bac:   'Eau bactériostatique (BAC) — Recommandé',
    solvent_water: 'Eau stérile pour injection',
    solvent_saline:'Sérum physiologique 0.9%',
    syringe_u30_label: 'U-30',
    syringe_u30_sub:   '0.3 mL — 30 unités · Mini doses',
    syringe_u50_label: 'U-50',
    syringe_u50_sub:   '0.5 mL — 50 unités · Doses moyennes',
    syringe_u100_label:'U-100',
    syringe_u100_sub:  '1.0 mL — 100 unités · Standard',
    syringe_u200_label:'2 mL',
    syringe_u200_sub:  '2.0 mL — Grandes doses / split-dose',

    // ── INVENTAIRE ───────────────────────────────────────────
    inv_title:         'Stock',
    inv_add:           '+ Ajouter un flacon',
    inv_vials:         'flacons',
    inv_low_stock:     'stock bas',
    inv_expired:       'expirés',
    inv_expired_badge: '⚠️ EXPIRÉ',
    inv_low_badge:     '⚠️ STOCK BAS',
    inv_sealed_badge:  '🔒 SCELLÉ',
    inv_modal_add:     'Ajouter un flacon',
    inv_modal_edit:    'Modifier le flacon',
    inv_peptide:       'Peptide',
    inv_peptide_ph:    'Ex: BPC-157, HGH…',
    inv_qty:           'Quantité totale',
    inv_unit:          'Unité',
    inv_dose_inj:      'Dose / injection',
    inv_frequency:     'Fréquence',
    inv_choose_freq:   '-- Choisir --',
    inv_recon_date:    'Date reconstitution',
    inv_status:        'Statut',
    inv_status_active: 'En cours',
    inv_status_sealed: 'Scellé',
    inv_status_done:   'Terminé',
    inv_temp:          '🌡 Temp. conservation',
    inv_temp_ph:       'ex: 2-8°C',
    inv_max_days:      '📅 Durée max (jours)',
    inv_storage_note:  'Note conservation',
    inv_storage_note_ph:'ex: Éviter la lumière',
    inv_note:          'Note (optionnel)',
    inv_note_ph:       'Ex: Lot 2025, cure récupération…',
    inv_save:          'Enregistrer le flacon',
    inv_cancel:        'Annuler',
    inv_inj_left:      'inj. restantes',
    inv_added:         '✓ Flacon ajouté',
    inv_updated:       '✓ Flacon mis à jour',
    inv_deleted:       'Flacon supprimé',
    inv_delete_confirm:'Supprimer ce flacon ?',
    inv_name_required: '⚠️ Nom du peptide requis',
    inv_empty:         'Aucun flacon enregistré.\nAjoutez votre premier flacon.',

    // ── IA ───────────────────────────────────────────────────
    ia_title:          'Conseiller IA',
    ia_online:         '● En ligne · Spécialiste peptides',
    ia_clear:          'Effacer',
    ia_context:        'Contexte :',
    ia_disclaimer:     '⚠️ Usage éducatif — Consultez un professionnel de santé avant tout protocole',
    ia_placeholder:    'Posez votre question sur les peptides…',
    ia_premium_title:  'Fonctionnalité Premium',
    ia_premium_sub:    'Le Conseiller IA est réservé aux membres Premium. Passez au plan Premium pour accéder aux conseils personnalisés.',
    ia_premium_btn:    '⭐ Passer Premium',
    ia_demo:           'Tester en mode démo',
    ia_error:          '⚠️ Erreur de connexion. Réessayez.',
    ia_quota:          'Quota mensuel atteint.',
    ia_clear_confirm:  'Effacer l\'historique de conversation ?',
    ia_hello:          'Bonjour{name} ! Je suis votre Conseiller IA spécialisé en peptides.',
    ia_mode_local:     'Mode base de connaissances locale — IA Claude bientôt disponible',

    ia_q_tendon:       '🔬 Quel peptide pour la récupération tendon ?',
    ia_q_nootropic:    '🧠 Peptides nootropiques pour la concentration ?',
    ia_q_recon:        '💉 Comment reconstituer le BPC-157 ?',
    ia_q_stack:        '🔄 Peut-on combiner BPC-157 et TB-500 ?',
    ia_q_epithalon:    '📅 Quelle durée pour une cure Epithalon ?',
    ia_q_bloodtest:    '🩸 Quels bilans sanguins surveiller ?',
    ia_q_sideeffects:  '🛡️ Quels effets secondaires surveiller ?',
    ia_q_sema:         '💊 Semaglutide : comment démarrer ?',
    ia_fallback_welcome: 'Bonjour{name} ! 👋\n\nJe suis votre Conseiller IA spécialisé en peptides. Posez-moi n\'importe quelle question sur :\n- Les dosages et protocoles\n- Les stacks synergiques\n- La reconstitution et conservation\n- Les effets et contre-indications\n\nQue souhaitez-vous savoir ?',
    // ── IA EXTRA ─────────────────────────────────────────────
    ia_ctx_cure:       'Cure active',
    ia_ctx_dosage:     'Dosage',
    ia_welcome_cure:   'Je vois que vous êtes au **Jour {day}** de votre cure **{peptide}**.\n\nJe peux vous aider avec :\n- Optimisation de votre protocole\n- Dosages et effets\n- Stacks synergiques\n- Bilans sanguins à surveiller\n\nQue souhaitez-vous savoir ?',
    ia_welcome_nocure: 'Je peux vous aider avec :\n- Choisir le bon peptide selon vos objectifs\n- Établir un protocole de cure complet\n- Comprendre les dosages et voies d\'administration\n- Créer des stacks synergiques\n\nQuelle est votre question ?',

    // ── CALCULATEUR ──────────────────────────────────────────
    calc_title:        'Calculateur',
    calc_warning:      'Outil d\'information uniquement',
    calc_warning_sub:  'Ce calculateur est un outil d\'information. Vérifiez toujours vos calculs avant toute injection. Consultez un professionnel de santé avant tout protocole. PeptideScanner décline toute responsabilité en cas d\'erreur de dosage.',
    calc_tab_recon:    '🧪 Reconstitution',
    calc_tab_dosage:   '💉 Dosage',
    calc_tab_titration:'📈 Titration',
    calc_tab_guide:    '📋 Guide injection',
    calc_recon_section:'Étape 1 — Calculer la concentration',
    calc_recon_title:  '🧪 Reconstitution du flacon',
    calc_peptide_qty:  'Quantité de peptide dans le flacon',
    calc_bac_volume:   'Volume d\'eau bactériostatique à ajouter',
    calc_recon_result: '✓ Résultat de la reconstitution',
    calc_dosage_section:'Calculer précisément votre dose',
    calc_dosage_title: '💉 Calculateur de dose précise',
    calc_dosage_sub:   'Entrez votre concentration (calculée dans l\'onglet Reconstitution) et la dose souhaitée.',
    calc_unit:         'Unité du peptide',
    calc_concentration:'Concentration du flacon reconstitué',
    calc_desired_dose: 'Dose souhaitée',
    calc_syringe:      'Type de seringue',
    calc_auto_syringe: '✓ Auto-sélectionnée',
    calc_dosage_result:'✓ Résultat du dosage',
    calc_titration_section:'Plan de titration progressive',
    calc_guide_section:'Guide d\'injection pas à pas',
    calc_guide_recon:  'Étapes de reconstitution',
    calc_guide_sc:     'Guide d\'injection sous-cutanée',
    calc_guide_warning_title: 'Avertissement médical',
    calc_guide_warning_sub: 'Ce guide est à titre éducatif uniquement. Toute injection doit être validée par un professionnel de santé. En cas de doute, ne pas procéder. PeptideScanner n\'est pas responsable des erreurs de manipulation ou de dosage.',
    calc_high_dose_title: 'Dose élevée détectée',
    calc_high_dose_confirm: 'J\'ai vérifié — continuer quand même',
    calc_high_dose_cancel:  '← Recalculer ma dose',
    calc_dose_table_dose: 'Dose',
    // ── ANALYTICS ────────────────────────────────────────────
    analytics_title:             'Analyse',
    analytics_30d:               '30 jours',
    analytics_60d:               '60 jours',
    analytics_90d:               '90 jours',
    analytics_all:               'Tout',
    analytics_scan_score:        'Scan Score',
    analytics_protocol_analysis: 'Analyse de votre protocole',
    analytics_excellent:         'Excellent',
    analytics_good:              'Bon',
    analytics_improve:           'À améliorer',
    analytics_weak:              'Faible',
    analytics_progression:       'Progression',
    analytics_regularity:        'Régularité',
    analytics_insights:          'Insights automatiques',
    analytics_cure_day:          'Jour de cure',
    analytics_expected:          'prévues',
    analytics_pace:              'Rythme',
    analytics_kg_week:           'kg / semaine',
    analytics_over:              'Sur',
    analytics_no_data:           'Pas encore assez de données pour générer des insights.',
    analytics_no_data_short:     'Pas assez de données',
    analytics_no_data_help:      'Ajoute au moins une cure active et 2 pesées.',
    analytics_empty_text:        'Pas encore assez de données pour analyser.<br>Commence une cure et enregistre ton poids régulièrement.',
    analytics_start_cure:        'Démarrer une cure →',
    analytics_heatmap:           'Heatmap des injections',
    analytics_weekly_compliance: 'Compliance par semaine',
    analytics_weight_proj:       'Projection poids',
    analytics_current_trend:     'Tendance actuelle',
    analytics_trend:             'Tendance',
    analytics_correlation:       'Corrélation poids × temps',
    analytics_compliance_excellent: 'Compliance excellente',
    analytics_compliance_good:   'Compliance correcte',
    analytics_compliance_weak:   'Compliance faible',
    analytics_weekend_drop:      'Compliance chute le weekend',
    analytics_weekend:           'Weekend',
    analytics_weekend_text:      'Tu es {pct}% moins régulier le weekend.',
    analytics_regular_weighing:  'Pesées régulières',
    analytics_regular:           'Régulier',
    analytics_add_weighing:      'Ajoute plus de pesées',
    analytics_gap:               'Gap de {n} jours sans pesée',
    analytics_gap_text:          'Tu as été absent {n} jours. Pèse-toi 2 fois par semaine.',
    analytics_since:             'Depuis',
    analytics_cure_days_weight:  'jours de cure, ton poids a',
    analytics_lost:              'diminué',
    analytics_gained:            'augmenté',
    analytics_you_lost:          'perdu',
    analytics_you_gained:        'pris',
    analytics_missed_inj:        'injections manquées',
    analytics_weight_evolution:  'Évolution poids',
    analytics_avg_gap:           'Moyenne de',
    analytics_add_weighing_text: 'Objectif : 2 pesées par semaine.',
    analytics_last_days:         'derniers jours',
    analytics_less:              'Moins',
    analytics_more:              'Plus',
    analytics_cure_end:          'Fin de cure',
    analytics_remaining_inj:     'Injections restantes',
    analytics_projected_weight:  'Poids projeté',
    analytics_projected_diff:    'Variation projetée',
    analytics_projected_compliance: 'Compliance projetée',
    // ── ANALYTICS ────────────────────────────────────────────
    analytics_title:             'Analyse',
    analytics_30d:               '30 jours',
    analytics_60d:               '60 jours',
    analytics_90d:               '90 jours',
    analytics_all:               'Tout',
    analytics_scan_score:        'Scan Score',
    analytics_protocol_analysis: 'Analyse de votre protocole',
    analytics_excellent:         'Excellent',
    analytics_good:              'Bon',
    analytics_improve:           'À améliorer',
    analytics_weak:              'Faible',
    analytics_progression:       'Progression',
    analytics_regularity:        'Régularité',
    analytics_insights:          'Insights automatiques',
    analytics_cure_day:          'Jour de cure',
    analytics_expected:          'prévues',
    analytics_pace:              'Rythme',
    analytics_kg_week:           'kg / semaine',
    analytics_over:              'Sur',
    analytics_no_data:           'Pas encore assez de données pour générer des insights.',
    analytics_no_data_short:     'Pas assez de données',
    analytics_no_data_help:      'Ajoute au moins une cure active et 2 pesées pour voir ton analyse.',
    analytics_empty_text:        'Pas encore assez de données pour analyser.<br>Commence une cure et enregistre ton poids régulièrement.',
    analytics_start_cure:        'Démarrer une cure →',
    analytics_heatmap:           'Heatmap des injections',
    analytics_weekly_compliance: 'Compliance par semaine',
    analytics_weight_proj:       'Projection poids',
    analytics_current_trend:     'Tendance actuelle',
    analytics_trend:             'Tendance',
    analytics_correlation:       'Corrélation poids × temps',
    analytics_compliance_excellent: 'Compliance excellente',
    analytics_compliance_good:   'Compliance correcte',
    analytics_compliance_weak:   'Compliance faible',
    analytics_weekend_drop:      'Compliance chute le weekend',
    analytics_weekend:           'Weekend',
    analytics_weekend_text:      'Tu es {pct}% moins régulier le weekend. Configure un rappel spécial samedi et dimanche.',
    analytics_regular_weighing:  'Pesées régulières',
    analytics_regular:           'Régulier',
    analytics_add_weighing:      'Ajoute plus de pesées',
    analytics_gap:               'Gap de {n} jours sans pesée',
    analytics_gap_text:          'Tu as été absent {n} jours. Pèse-toi au minimum 2 fois par semaine.',
    analytics_since:             'Depuis',
    analytics_cure_days_weight:  'jours de cure, ton poids a',
    analytics_lost:              'perdu',
    analytics_gained:            'pris',
    analytics_you_lost:          'perdu',
    analytics_you_gained:        'pris',
    analytics_missed_inj:        'injections manquées',
    analytics_weight_evolution:  'Évolution poids',
    analytics_avg_gap:           'Moyenne de',
    analytics_add_weighing_text: 'Objectif : 2 pesées par semaine.',
    analytics_last_days:         'derniers jours',
    analytics_less:              'Moins',
    analytics_more:              'Plus',
    analytics_cure_end:          'Fin de cure',
    analytics_remaining_inj:     'Injections restantes',
    analytics_projected_weight:  'Poids projeté',
    analytics_projected_diff:    'Variation projetée',
    analytics_projected_compliance: 'Compliance projetée',
    // ── ANALYTICS ────────────────────────────────────────────
    analytics_title:          'Analytics',
    analytics_protocol_title: 'Protocol analysis',
    analytics_compliance:     'Compliance',
    analytics_progression:    'Progression',
    analytics_regularity:     'Regularity',
    analytics_score_exc:      'Excellent',
    analytics_score_good:     'Good',
    analytics_score_avg:      'To improve',
    analytics_score_low:      'Low',
    analytics_insights:       'Automatic insights',
    analytics_no_data:        'Not enough data yet to generate insights.',
    analytics_injections:     'Injections',
    analytics_planned:        'planned',
    analytics_cure_day:       'Cycle day',
    analytics_rate:           'Rate',
    analytics_kg_week:        'kg / week',
    analytics_over:           'over',
    analytics_corr_title:     'Weight × time correlation',
    analytics_weight_evolution:'Weight progress',
    analytics_weight_label:   'Weight',
    analytics_trend:          'Trend',
    analytics_cure_start:     'Cycle start',
    analytics_week_short:     'W',
    analytics_compliance_exc: 'Excellent compliance',
    analytics_compliance_ok:  'Good compliance',
    analytics_compliance_low: 'Low compliance',
    analytics_weekend_drop:   'Compliance drops on weekends',
    analytics_weight_evo:     'Weight evolution',
    analytics_regular_weighing:'Regular weigh-ins',
    analytics_regular:        'Regular',
    analytics_add_weighing:   'Add more weigh-ins',
    analytics_projection:     'Cycle end projection',
    analytics_gap:            'Gap of',
    analytics_empty_title:    'No data yet',
    analytics_empty_sub:      'Start a cycle or add weight measurements to see your personalized analysis.',
    analytics_weekend:        'on weekends',
    analytics_weekday:        'on weekdays',
    analytics_since_start:    'Since cycle start',
    analytics_weekly_compliance:'Weekly compliance',
    // ── ANALYTICS ────────────────────────────────────────────
    analytics_title:          'Analyse',
    analytics_protocol_title: 'Analyse de votre protocole',
    analytics_compliance:     'Compliance',
    analytics_progression:    'Progression',
    analytics_regularity:     'Régularité',
    analytics_score_exc:      'Excellent',
    analytics_score_good:     'Bon',
    analytics_score_avg:      'À améliorer',
    analytics_score_low:      'Faible',
    analytics_insights:       'Insights automatiques',
    analytics_no_data:        'Pas encore assez de données pour générer des insights.',
    analytics_injections:     'Injections',
    analytics_planned:        'prévues',
    analytics_cure_day:       'Jour de cure',
    analytics_rate:           'Rythme',
    analytics_kg_week:        'kg / semaine',
    analytics_over:           'sur',
    analytics_corr_title:     'Corrélation poids × temps',
    analytics_weight_evolution:'Évolution du poids',
    analytics_weight_label:   'Poids',
    analytics_trend:          'Tendance',
    analytics_cure_start:     'Début cure',
    analytics_week_short:     'S',
    analytics_compliance_exc: 'Compliance excellente',
    analytics_compliance_ok:  'Compliance correcte',
    analytics_compliance_low: 'Compliance faible',
    analytics_weekend_drop:   'Compliance chute le weekend',
    analytics_weight_evo:     'Évolution poids',
    analytics_regular_weighing:'Pesées régulières',
    analytics_regular:        'Régulier',
    analytics_add_weighing:   'Ajoute plus de pesées',
    analytics_projection:     'Projection fin de cure',
    analytics_gap:            'Gap de',
    analytics_empty_title:    'Pas encore de données',
    analytics_empty_sub:      'Commencez une cure ou ajoutez des mesures de poids pour voir votre analyse personnalisée.',
    analytics_weekend:        'le weekend',
    analytics_weekday:        'en semaine',
    analytics_since_start:    'Depuis le début de la cure',
    analytics_weekly_compliance:'Compliance hebdomadaire',

    // ── PEPTIDE DATABASE ─────────────────────────────────────
    db_eyebrow:          'Bibliothèque · Base de données',
    db_title:            'Référentiel peptidique complet',
    db_sub:              'Chaque peptide référencé avec ses dosages, protocoles, effets et stacks recommandés.',
    db_stat_peptides:    'Peptides référencés',
    db_stat_categories:  'Catégories',
    db_stat_shown:       'Affichés',
    db_search_ph:        'Rechercher un peptide, effet, catégorie…',
    db_all:              'Tous',
    db_cat_recov:        'Récupération',
    db_cat_anti:         'Anti-âge',
    db_cat_neuro:        'Neuro',
    db_cat_fat:          'Poids',
    db_cat_sex:          'Sexuel',
    db_cat_immun:        'Immunité',
    db_cat_cardio:       'Cardio',
    db_cat_skin:         'Peau',
    db_guide_title:      '📊 Guide — Avancement de la recherche',
    db_dosage:           'Dosage',
    db_duration:         'Durée',
    db_stack_with:       'Stack avec',
    db_buy:              'Acheter →',
    db_no_results_msg:   'Aucun peptide trouvé pour "{q}".',
    db_no_results_sub:   'Essayez un autre mot-clé.',
    db_modal_dosage:     'Dosage typique',
    db_modal_admin:      'Administration',
    db_modal_duration:   'Durée de cure',
    db_modal_freq:       'Fréquence',
    db_modal_protocol:   'Protocole détaillé',
    db_modal_effects:    'Effets principaux',
    db_modal_side_effects:'Effets secondaires',
    db_modal_stacks:     'Stacks recommandés',
    db_modal_contra:     'Contre-indications',
    db_modal_note:       'Note experte',
    db_modal_find:       'Trouver {name} chez un fournisseur vérifié',
    db_modal_shops:      'Voir les boutiques →',
    db_modal_disclaimer: '⚠️ Usage éducatif uniquement. Ces peptides sont à usage de recherche. Consultez impérativement un professionnel de santé avant tout usage.',
    db_disclaimer_title: 'Avertissement légal — Usage éducatif et informatif uniquement.',
    db_disclaimer_body:  'Les peptides présentés sont des peptides de recherche. Leur acquisition, détention ou usage peut être illégal dans votre pays. Les informations ne constituent pas un avis médical. Consultez un professionnel de santé avant tout protocole.',
    // ── PHASES DE RECHERCHE ──────────────────────────────────
    phase_exp_label:     'Données limitées',
    phase_pre_label:     'Recherche animale',
    phase_p1_label:      'Premiers tests humains',
    phase_p2_label:      'Études en cours',
    phase_p3_label:      'Études avancées',
    phase_est_label:     'Largement utilisé',
    phase_exp_desc:      'Très peu d\'études disponibles',
    phase_pre_desc:      'Testé uniquement sur des animaux',
    phase_p1_desc:       'Sécurité vérifiée sur quelques personnes',
    phase_p2_desc:       'Efficacité testée sur des centaines de personnes',
    phase_p3_desc:       'Testé sur des milliers — proche du marché',
    phase_est_desc:      'Retours abondants, profil bien documenté',
    phase_exp_desc_dot:  'Très peu d\'études disponibles.',
    phase_pre_desc_dot:  'Testé uniquement sur des animaux.',
    phase_p1_desc_dot:   'Sécurité vérifiée sur quelques volontaires.',
    phase_p2_desc_dot:   'Testé sur des centaines de personnes.',
    phase_p3_desc_dot:   'Testé sur des milliers — approbation proche.',
    phase_est_desc_dot:  'Retours abondants, profil bien documenté.',
    phase_step1:         'Recherche',
    phase_step2:         'Tests',
    phase_step3:         'Études',
    phase_step4:         'Avancé',
    phase_step5:         'Établi',
    // ── IA CONTEXT ────────────────────────────────────────────
    ia_ctx_user:     'Utilisateur',
    ia_ctx_goal:     'Objectif',
    ia_ctx_weight:   'Dernier poids',
    ia_q1:           '⚖️ Meilleur protocole perte de poids ?',
    ia_q2:           '💪 Stack optimal pour prise de masse ?',
    ia_q3:           '⚡ CJC-1295 avec ou sans DAC ?',
    ia_q4:           '❄️ Comment conserver les peptides ?',
    ia_q1:           '⚖️ Best weight loss protocol?',
    ia_q2:           '💪 Optimal stack for muscle gain?',
    ia_q3:           '⚡ CJC-1295 with or without DAC?',
    ia_q4:           '❄️ How to store peptides?',
    // ── GOALS ────────────────────────────────────────────────
    goal_fat_loss:   'Fat loss',
    goal_muscle:     'Muscle gain',
    goal_performance:'Performance',
    goal_anti_age:   'Anti-aging',
    goal_recovery:   'Recovery',
    goal_health:     'General health',
    // ── DASHBOARD EXTRA ──────────────────────────────────────
    dash_all_cures:  'all cycles',
    // ── INVENTAIRE EXTRA ─────────────────────────────────────
    inv_add_vial:    'Add a vial',
    // ── CALCULATEUR EXTRA ────────────────────────────────────
    calc_other_volume:       'Other volume:',
    calc_why_water:          '💡 Why water volume matters',
    calc_understand_syringe: '🔬 Understanding U-100 insulin syringe',

    // ── IA CONTEXT ───────────────────────────────────────────
    ia_ctx_user:     'Utilisateur',
    ia_ctx_goal:     'Objectif',
    ia_ctx_weight:   'Dernier poids',
    ia_q1:           '⚖️ Meilleur protocole perte de poids ?',
    ia_q2:           '💪 Stack optimal pour prise de masse ?',
    ia_q3:           '⚡ CJC-1295 avec ou sans DAC ?',
    ia_q4:           '❄️ Comment conserver les peptides ?',
    // ── GOALS ────────────────────────────────────────────────
    goal_fat_loss:   'Perte de graisse',
    goal_muscle:     'Prise de masse',
    goal_performance:'Performance',
    goal_anti_age:   'Anti-âge',
    goal_recovery:   'Récupération',
    goal_health:     'Santé générale',
    // ── DASHBOARD EXTRA ──────────────────────────────────────
    dash_all_cures:  'toutes cures',
    // ── INVENTAIRE EXTRA ─────────────────────────────────────
    inv_add_vial:    'Ajouter un flacon',
    // ── CALCULATEUR EXTRA ────────────────────────────────────
    calc_other_volume:       'Autre volume :',
    calc_why_water:          '💡 Pourquoi le volume d\'eau est crucial',
    calc_understand_syringe: '🔬 Comprendre la seringue insuline U-100',


    // ── SITES D'INJECTION ────────────────────────────────────
    site_abd_g:      'Abdomen gauche',
    site_abd_d:      'Abdomen droit',
    site_thigh_g:    'Cuisse gauche',
    site_thigh_d:    'Cuisse droite',
    site_glute_g:    'Fesse gauche',
    site_glute_d:    'Fesse droite',
    site_deltoid_g:  'Deltoïde gauche',
    site_deltoid_d:  'Deltoïde droit',
    zone_abdomen:    'Abdomen',
    zone_thigh:      'Cuisse',
    zone_glute:      'Fessier',
    zone_shoulder:   'Épaule',
    zone_arm:        'Bras',
    site_quad_g:     'Quadriceps gauche',
    site_quad_d:     'Quadriceps droit',
    // ── CALCULATEUR EXTRA ────────────────────────────────────
    calc_units:      'unités',
    calc_verification: 'Vérification',
    days_suffix:     'j',

    // ── CALCULATEUR TITRATION ────────────────────────────────
    calc_phase_adapt:    'Phase d\'adaptation',
    calc_increase:       'Augmentation progressive',
    calc_eff_dose:       'Dose efficace',
    calc_adv_dose:       'Dose avancée',
    calc_max_dose:       'Dose maximale',
    calc_prog_rise:      'Montée progressive',
    calc_load_phase:     'Phase de charge',
    calc_maint_phase:    'Phase entretien',
    calc_intensive:      'Cure intensive',
    calc_mandatory_break:'Pause obligatoire',
    calc_second_cycle:   '2ème cure annuelle',
    calc_adapt:          'Adaptation',
    calc_high_dose_label:'Dose haute',
    calc_warn_bpc_stack: 'Stack avec BPC-157 pour synergie optimale',
    calc_warn_6months:   'Ne pas répéter avant 6 mois',
    calc_warn_2year:     'Maximum 2 cures par an',
    calc_warn_titration: 'Titration obligatoire — ne jamais sauter d\'étapes',
    calc_warn_maxdose:   'Ne pas dépasser 2.4 mg/semaine sans suivi médical',
    calc_approx:         'environ',
    calc_at_500:         'à 500mcg/jour (2×250mcg)',
    calc_sem_s1_exp:     'Légères nausées possibles, évaluation tolérance',
    calc_sem_s2_exp:     'Réduction notable de l\'appétit',
    calc_sem_s3_exp:     'Perte de poids régulière 0.5–1 kg/semaine',
    calc_sem_s4_exp:     'Perte de poids accélérée',
    calc_sem_s5_exp:     'Effet maximal — dose approuvée FDA',
    calc_tir_s1_exp:     'Nausées légères, habituation GIP+GLP1',
    calc_tir_s2_exp:     '↓ Appétit significatif',
    calc_bpc_s1_exp:     'Régénération systémique, flexibilité améliorée, réduction fibrose',
    calc_bpc_s2_exp:     'Maintien des effets, prévention blessures récurrentes',
    calc_tb_s1_exp:      'Régénération systémique',
    calc_epi_s1_exp:     'Allongement des télomères, amélioration sommeil, énergie',
    calc_epi_s2_exp:     'Laisser le temps aux télomères de se consolider',
    calc_epi_s3_exp:     'Renforcement des effets anti-âge cumulatifs',
    calc_week:           '1×/semaine',
    calc_warn_semlow:    'Si nausées persistantes — rester à 0.25mg',
    calc_warn_sem1mg:    'Uniquement si 1mg bien toléré',
    calc_warn_tol:       'Évaluer la tolérance avant d\'augmenter',
    calc_warn_prev_tol:  '⚠️ Uniquement si doses précédentes bien tolérées',
    calc_warn_absmax:    '⚠️ Dose maximale — Ne jamais dépasser',
    calc_warn_exp_p3:    'Peptide expérimental — phase 3 clinique',
    calc_warn_hr:        'Surveiller fréquence cardiaque (max 100 bpm repos)',
    calc_warn_exp_only:  '⚠️ Non approuvé — Recherche uniquement. Suivi médical obligatoire',
    calc_warn_fast:      'Respecter 2h de jeûn avant injection',
    calc_warn_igf1:      'Vérifier IGF-1 à J30',
    calc_warn_no_continuous: '⚠️ Ne pas utiliser en continu sans pause',
    calc_warn_inject_near:   'Injecter près de la zone à traiter',
    calc_appetite_down:  '↓ Appétit',
    calc_fat_loss:       'Perte de graisse',
    calc_major_loss:     'Perte majeure',
    calc_max_effect:     'Effet maximal',
    calc_intro:          'Introduction',
    calc_eff_phase:      'Phase efficace',
    calc_opt_dose:       'Dose optimale',
    calc_cycle_off:      'Cycle OFF obligatoire',
    calc_break_4w:       'Pause 4 semaines',
    calc_break_6m:       'Pause 6 mois',
    calc_2nd_cycle:      '2ème cure',
    calc_therap_phase:   'Phase thérapeutique',
    calc_tir_s3_exp:     'Perte de poids rapide, amélioration glycémie',
    calc_tir_s4_exp:     'Effets maximaux sur la composition corporelle',
    calc_tir_s5_exp:     'Résultats optimaux pour la plupart des patients',
    calc_tir_s6_exp:     'Dose maximale approuvée — maintenir si bien toléré',
    calc_ret_s1_exp:     'Nausées légères, habituation du corps',
    calc_ret_s2_exp:     'Réduction de l\'appétit nette, perte de poids début',
    calc_ret_s3_exp:     'Perte de graisse viscérale visible, énergie améliorée',
    calc_ret_s4_exp:     'Perte de poids significative, remodelage corporel',
    calc_ret_s5_exp:     'Résultats maximaux des études cliniques de phase 2',
    calc_cjc_s1_exp:     'Adaptation, flush léger possible, meilleur sommeil dès J3-5',
    calc_cjc_s2_exp:     '↑ GH nocturne, récupération améliorée, composition corporelle',
    calc_cjc_s3_exp:     'Effets maximaux GH, lipolyse, sommeil profond',
    calc_cjc_s4_exp:     'Permettre la récupération de l\'axe GH naturel',
    calc_bpc_intro_exp:  'Premiers effets anti-inflammatoires, réduction douleur J5-10',
    calc_bpc_therap_exp: 'Régénération tissulaire, cicatrisation, protection gastrique',
    calc_bpc_maint_exp:  'Maintien des effets, consolidation de la guérison',
  },

  // ══════════════════════════════════════════════════════════
  en: {
    // ── NAV ──────────────────────────────────────────────────
    nav_home:       'Home',
    nav_cure:       'Cycle',
    nav_calc:       'Calc',
    nav_stock:      'Stock',
    nav_alerts:     'Alerts',
    nav_profile:    'Profile',
    nav_biblio:     'Library',
    nav_weight:     'Weight',
    nav_ia:         'AI',
    nav_analyse:    'Analytics',

    // ── COMMON ───────────────────────────────────────────────
    save:           'Save',
    cancel:         'Cancel',
    delete:         'Delete',
    edit:           'Edit',
    add:            'Add',
    confirm:        'Confirm',
    close:          'Close',
    loading:        'Loading…',
    error:          'Error',
    success:        'Success',
    optional:       'optional',
    all:            'All',
    none:           'None',
    days:           'days',
    day:            'day',
    today:          'Today',
    week:           'week',
    month:          'month',
    yes:            'Yes',
    no:             'No',
    back:           'Back',
    next:           'Next',
    see_all:        'See all →',
    details:        'Detail →',
    no_data:        'No data',

    // ── DISCLAIMER ───────────────────────────────────────────
    disclaimer_title: 'Educational use only',
    disclaimer_short: 'Research peptides not approved for human use. Consult a healthcare professional. PeptideScanner disclaims all liability.',
    disclaimer_icon:  '⚠️',

    // ── DASHBOARD ────────────────────────────────────────────
    dash_greeting:        'Hello 👋',
    dash_active_cure:     'Active cycle',
    dash_protocol:        'Current protocol',
    dash_no_cure:         'No active cycle',
    dash_no_cure_sub:     'Tap "+ New cycle" to get started',
    dash_day_label:       '/ days',
    dash_calendar:        '📅 Calendar',
    dash_new_cure:        '＋ New cycle',
    dash_summary:         'Summary',
    dash_weight_title:    'Weight progress',
    dash_today_section:   'Today',
    dash_calendar_link:   'Calendar →',
    dash_alerts_section:  'Recent alerts',
    dash_alerts_all:      'All →',
    dash_no_alerts:       'No active alerts 🎉',
    dash_weight_go:       'Weight →',
    dash_inj_done:        'Injections done',
    dash_days_left:       'Days remaining',
    dash_end_date:        'Estimated end',
    dash_compliance:      'Compliance',
    dash_cures_done:      'Completed cycles',
    dash_total_inj:       'Total injections',
    dash_current_weight:  'Current weight',
    dash_since_start:     'since start',
    dash_first_measure:   'First measure',
    dash_no_weight_data:  'No data — Add your weight',
    dash_score_label:     'doses done',
    dash_score_done:      '✅ Complete',
    dash_today_program:   "Today's schedule",
    dash_no_injection:    'No injection scheduled today.',
    dash_injection_day:   'Daily injection',
    dash_injection_num:   'Injection',
    dash_confirm_inj:     'Confirm injection',
    dash_check_time:      'Check the time before confirming',
    dash_inj_time:        '⏰ Injection time',
    dash_validate:        '✓ Confirm injection',
    dash_new_cure_title:  'New cycle',
    dash_peptide:         'Peptide',
    dash_choose_peptide:  'Choose a peptide…',
    dash_dosage:          'Dosage',
    dash_admin:           'Route',
    dash_start_date:      'Start date',
    dash_duration:        'Duration (days)',
    dash_frequency:       'Injection frequency',
    dash_start_cure:      'Start cycle',
    dash_cure_ended:      'Cycle ends in',
    dash_days_suffix:     'd',
    dash_inj_cancelled:   'Injection cancelled',
    dash_inj_saved:       '— saved!',
    freq_1x:    '1× per day',
    freq_2x:    '2× per day',
    freq_3x:    '3× per day',
    freq_1_2d:  'Every 2 days',
    freq_2x_w:  '2× per week',
    freq_1x_w:  '1× per week',
    admin_sc:   'SC',
    admin_im:   'IM',
    admin_oral: 'Oral',
    admin_nasal:'Nasal',
    admin_iv:   'IV',

    // ── CURE ─────────────────────────────────────────────────
    cure_title:         'Cycle calendar',
    cure_status_active: 'Active',
    cure_status_ended:  'Completed',
    cure_status_future: 'Upcoming',
    cure_dosage:        'Dosage',
    cure_frequency:     'Frequency',
    cure_duration:      'Duration',
    cure_start:         'Start',
    cure_end:           'End',
    cure_remaining:     'Remaining',
    cure_compliance:    'Compliance',
    cure_edit:          '✏️ Edit',
    cure_stats:         'Statistics',
    cure_inj_done:      'Injections done',
    cure_inj_expected:  'Expected injections',
    cure_inj_missed:    'Missed',
    cure_current_day:   'Current day',
    cure_new:           'New cycle',
    cure_start_btn:     'Start cycle',
    cure_save_btn:      'Save',
    cure_delete_btn:    'Delete this cycle',
    cure_empty:         'No cycle recorded.\nStart by adding your first protocol.',
    cure_add_first:     '+ New cycle',
    cure_notes:         'Notes (optional)',
    cure_notes_ph:      'Goal, remarks…',
    cure_modal_edit:    'Edit cycle',
    cure_suggested_site:'Suggested site',
    cure_change_site:   'Change →',
    cure_zone:          'Zone:',
    cure_rest_day:      'Rest day 😴',
    cure_save_note:     'Save note',
    cure_note_ph:       'Note for this day…',
    cure_note_saved:    '✓ Note saved',
    cure_legend_done:   'Done',
    cure_legend_partial:'Partial',
    cure_legend_missed: 'Missed',
    cure_legend_planned:'Planned',
    cure_legend_rest:   'Rest',
    cure_time_updated:  '✓ Time updated: ',
    cure_inj_done_msg:  '✓ Injection — ',
    cure_inj_cancelled: 'Injection cancelled',
    cure_deleted:       'Cycle deleted',
    cure_updated:       '✓ Cycle updated',
    cure_started:       '✓ Cycle started!',
    cure_confirm_delete:'Delete this cycle?',
    cure_choose:        'Choose…',
    // ── TITRATION ─────────────────────────────────────────────
    titration_title:      'Progressive titration',
    titration_sub:        'Progressive dose steps (max 4)',
    titration_add_palier: 'Add a step',
    titration_palier:     'Step',
    titration_duration:   'Duration (days)',
    titration_info:       'Main dose will be ignored — each step defines its own dose.',
    cure_my_stock:      '🧪 My stock',
    cure_library:       '📚 Library',
    days_short:         ['M','T','W','T','F','S','S'],
    months:             ['January','February','March','April','May','June','July','August','September','October','November','December'],

    // ── POIDS ────────────────────────────────────────────────
    weight_title:       'Weight tracking',
    weight_period_7:    '7d',
    weight_period_30:   '30d',
    weight_period_90:   '3 months',
    weight_period_all:  'All',
    weight_current:     'current kg',
    weight_variation:   'change',
    weight_measures:    'entries',
    weight_chart_title: 'Progress',
    weight_add_title:   'Log my weight',
    weight_add_btn:     'Add',
    weight_note_ph:     'Note (optional)',
    weight_date:        'Date',
    weight_bmi_title:   'BMI',
    weight_history:     'History',
    weight_no_data:     'No data',
    weight_add_first:   'Add your first weight',
    weight_saved:       '✓ Weight saved: ',
    weight_deleted:     'Entry deleted',
    weight_modified:    '✓ Weight updated',
    weight_invalid:     '⚠️ Invalid weight',
    weight_date_req:    '⚠️ Date required',
    weight_height_title:'📏 Your height?',
    weight_height_sub:  'Required to calculate your BMI correctly.',
    weight_height_ph:   '178',
    weight_height_ok:   'OK',
    weight_height_saved:'✓ Height saved',
    weight_height_first:'📏 Enter your height first',
    weight_height_inv:  '⚠️ Invalid height',
    weight_bmi_under:   'Underweight',
    weight_bmi_normal:  'Normal weight ✓',
    weight_bmi_over:    'Overweight',
    weight_bmi_obese:   'Obesity',
    weight_bmi_unit:    'cm · Weight:',
    weight_bmi_height:  'Height:',

    // ── ALERTES ──────────────────────────────────────────────
    alerts_title:       'Alerts',
    alerts_notif_title: 'Smart notifications',
    alerts_notif_sub:   'Receive injection reminders even when the app is closed',
    alerts_enable:      'Enable',
    alerts_enabled:     '✓ Enabled — Disable',
    alerts_blocked:     'Blocked ⚠️',
    alerts_reminders:   'Injection reminders',
    alerts_no_active:   'No active cycle',
    alerts_schedule:    "Today's schedule",
    alerts_auto:        'Active alerts',
    alerts_custom:      'My reminders',
    alerts_add_title:   '+ New reminder',
    alerts_msg_label:   'Message',
    alerts_msg_ph:      'e.g.: IGF-1 blood test',
    alerts_date:        'Date',
    alerts_time:        'Time',
    alerts_priority:    'Priority',
    alerts_prio_normal: 'Normal',
    alerts_prio_high:   'Important',
    alerts_prio_urgent: 'Urgent',
    alerts_save_btn:    'Save reminder',
    alerts_no_auto:     'No automatic alerts 🎉',
    alerts_no_custom:   'No reminders — add one above',
    alerts_no_today:    'No injection today',
    alerts_done:        '✓ Done',
    alerts_due:         '⏰ Due',
    alerts_upcoming:    'Upcoming',
    alerts_added:       '✓ Reminder added!',
    alerts_deleted:     'Reminder deleted',
    alerts_notif_on:    '🔔 Reminder enabled',
    alerts_notif_off:   '🔕 Reminder disabled',
    alerts_time_saved:  '✓ Time updated — ',
    alerts_cure_end:    'Cycle ends in',
    alerts_blood_test:  'Blood test recommended',
    alerts_inj_label:   'Injection',
    alerts_inj_day:     'of the day',
    alerts_fill_all:    '⚠️ Fill all fields',
    alerts_notif_unsupported: 'Not supported on this browser',
    alerts_notif_activated: '✓ Notifications enabled!',
    alerts_notif_refused: 'Notifications denied — check Safari settings',
    alerts_notif_disabled: '🔕 Notifications disabled',
    alerts_blocked_help:   '⚙️ Allow notifications in Safari Settings → Websites → Notifications',

    // ── PROFIL ───────────────────────────────────────────────
    profil_title:       'My profile',
    profil_plan_free:   'Free plan',
    profil_plan_prem:   '⭐ Premium',
    profil_info:        'Personal information',
    profil_name:        'First name',
    profil_age:         'Age',
    profil_height:      'Height',
    profil_goal:        'Goal',
    profil_stats:       'My statistics',
    profil_subscription:'Subscription',
    profil_equipment:   'My equipment',
    profil_syringes:    '💉 My syringes',
    profil_syringes_sub:'Select the syringes you own. The calculator will adapt automatically.',
    profil_needle_type: '🧪 Preferred needle type',
    profil_solvent:     '💧 Preferred reconstitution solvent',
    profil_settings:    'Settings',
    profil_biblio_link: 'Peptide library',
    profil_export:      'Export my data',
    profil_export_sub:  'JSON — all my cycles and measurements',
    profil_home_link:   'Home page',
    profil_home_sub:    'Back to landing page',
    profil_danger:      'Danger zone',
    profil_logout:      '🚪 Sign out',
    profil_reset:       '🗑 Delete all my data',
    profil_version:     'PeptideScanner v1.0 · Educational use only',
    profil_total_cures: 'Total cycles',
    profil_injections:  'Injections',
    profil_done_cures:  'Finished cycles',
    profil_weight_var:  'Weight change',
    profil_prem_active: '⭐ Premium active',
    profil_prem_active_sub: 'You have access to all premium features.',
    profil_upgrade:     'Go Premium',
    profil_upgrade_sub: 'Unlock full tracking, smart alerts and AI advisor.',
    profil_upgrade_btn: '⭐ Subscribe — €59 / year',
    profil_feat1:       'Unlimited cycle calendar',
    profil_feat2:       'Weight tracking + charts',
    profil_feat3:       'Alerts & push reminders',
    profil_feat4:       'Specialized AI advisor',
    profil_feat5:       'Unlimited cycles & calendar',
    profil_feat6:       'Full weight tracking',
    profil_feat7:       'Unlimited AI advisor',
    profil_logout_confirm: 'Sign out?',
    profil_reset_confirm1: '⚠️ Delete ALL data? Irreversible.',
    profil_reset_confirm2: 'Really delete everything?',
    profil_reset_done:  'Data deleted',
    profil_export_done: '✓ Data exported',
    profil_pseudo_title:'Choose your username',
    profil_pseudo_ph:   'e.g.: James',
    profil_pseudo_saved:'✓ Username saved!',
    profil_updated:     '✓ updated',
    profil_not_filled:  'Not set',
    profil_biblio_count:'52 peptides referenced',
    profil_prem_activated: '⭐ Premium activated!',
    profil_lang:        'Language',
    profil_lang_sub:    'Français / English',
    needle_4mm:  '4 mm — Very thin (SC abdominal)',
    needle_6mm:  '6 mm — Standard SC',
    needle_8mm:  '8 mm — Shallow SC/IM',
    needle_12mm: '12 mm — Deep IM',
    needle_25mm: '25 mm — IM deltoid',
    solvent_bac:   'Bacteriostatic water (BAC) — Recommended',
    solvent_water: 'Sterile water for injection',
    solvent_saline:'Normal saline 0.9%',
    syringe_u30_label: 'U-30',
    syringe_u30_sub:   '0.3 mL — 30 units · Mini doses',
    syringe_u50_label: 'U-50',
    syringe_u50_sub:   '0.5 mL — 50 units · Medium doses',
    syringe_u100_label:'U-100',
    syringe_u100_sub:  '1.0 mL — 100 units · Standard',
    syringe_u200_label:'2 mL',
    syringe_u200_sub:  '2.0 mL — Large doses / split-dose',

    // ── INVENTAIRE ───────────────────────────────────────────
    inv_title:         'Stock',
    inv_add:           '+ Add vial',
    inv_vials:         'vials',
    inv_low_stock:     'low stock',
    inv_expired:       'expired',
    inv_expired_badge: '⚠️ EXPIRED',
    inv_low_badge:     '⚠️ LOW STOCK',
    inv_sealed_badge:  '🔒 SEALED',
    inv_modal_add:     'Add a vial',
    inv_modal_edit:    'Edit vial',
    inv_peptide:       'Peptide',
    inv_peptide_ph:    'e.g.: BPC-157, HGH…',
    inv_qty:           'Total quantity',
    inv_unit:          'Unit',
    inv_dose_inj:      'Dose / injection',
    inv_frequency:     'Frequency',
    inv_choose_freq:   '-- Choose --',
    inv_recon_date:    'Reconstitution date',
    inv_status:        'Status',
    inv_status_active: 'Active',
    inv_status_sealed: 'Sealed',
    inv_status_done:   'Finished',
    inv_temp:          '🌡 Storage temp.',
    inv_temp_ph:       'e.g.: 2-8°C',
    inv_max_days:      '📅 Max duration (days)',
    inv_storage_note:  'Storage note',
    inv_storage_note_ph:'e.g.: Keep away from light',
    inv_note:          'Note (optional)',
    inv_note_ph:       'e.g.: Lot 2025, recovery cycle…',
    inv_save:          'Save vial',
    inv_cancel:        'Cancel',
    inv_inj_left:      'injections left',
    inv_added:         '✓ Vial added',
    inv_updated:       '✓ Vial updated',
    inv_deleted:       'Vial deleted',
    inv_delete_confirm:'Delete this vial?',
    inv_name_required: '⚠️ Peptide name required',
    inv_empty:         'No vials recorded.\nAdd your first vial.',

    // ── IA ───────────────────────────────────────────────────
    ia_title:          'AI Advisor',
    ia_online:         '● Online · Peptide specialist',
    ia_clear:          'Clear',
    ia_context:        'Context:',
    ia_disclaimer:     '⚠️ Educational use — Consult a healthcare professional before any protocol',
    ia_placeholder:    'Ask your peptide question…',
    ia_premium_title:  'Premium feature',
    ia_premium_sub:    'The AI Advisor is reserved for Premium members. Upgrade to access personalized advice.',
    ia_premium_btn:    '⭐ Go Premium',
    ia_demo:           'Try demo mode',
    ia_error:          '⚠️ Connection error. Please retry.',
    ia_quota:          'Monthly quota reached.',

    // ── IA CONTEXT ────────────────────────────────────────────
    ia_ctx_user:     'User',
    ia_ctx_goal:     'Goal',
    ia_ctx_weight:   'Last weight',
    ia_q1:           '⭐ Best weight loss protocol?',
    ia_q2:           '💪 Optimal stack for muscle gain?',
    ia_q3:           '⚡ CJC-1295 with or without DAC?',
    ia_q4:           '❄️ How to store peptides?',
    ia_clear_confirm:  'Clear conversation history?',
    ia_hello:          'Hello{name}! I am your specialized AI Peptide Advisor.',
    ia_mode_local:     'Local knowledge base mode — Claude AI coming soon',

    ia_q_tendon:       '🔬 Quel peptide pour la récupération tendon ?',
    ia_q_nootropic:    '🧠 Peptides nootropiques pour la concentration ?',
    ia_q_recon:        '💉 Comment reconstituer le BPC-157 ?',
    ia_q_stack:        '🔄 Peut-on combiner BPC-157 et TB-500 ?',
    ia_q_epithalon:    '📅 Quelle durée pour une cure Epithalon ?',
    ia_q_bloodtest:    '🩸 Quels bilans sanguins surveiller ?',
    ia_q_sideeffects:  '🛡️ Quels effets secondaires surveiller ?',
    ia_q_sema:         '💊 Semaglutide : comment démarrer ?',

    ia_q_tendon:       '🔬 Which peptide for tendon recovery?',
    ia_q_nootropic:    '🧠 Nootropic peptides for focus?',
    ia_q_recon:        '💉 How to reconstitute BPC-157?',
    ia_q_stack:        '🔄 Can you combine BPC-157 and TB-500?',
    ia_q_epithalon:    '📅 What duration for an Epithalon cycle?',
    ia_q_bloodtest:    '🩸 Which blood tests to monitor?',
    ia_q_sideeffects:  '🛡️ Which side effects to watch for?',
    ia_q_sema:         '💊 Semaglutide: how to start?',
    ia_fallback_welcome: 'Hello{name}! 👋\n\nI am your specialized AI Peptide Advisor. Ask me anything about:\n- Dosages and protocols\n- Synergistic stacks\n- Reconstitution and storage\n- Effects and contraindications\n\nWhat would you like to know?',
    // ── IA EXTRA ─────────────────────────────────────────────
    ia_ctx_cure:       'Active cycle',
    ia_ctx_dosage:     'Dosage',
    ia_welcome_cure:   'I can see you are on **Day {day}** of your **{peptide}** cycle.\n\nI can help you with:\n- Protocol optimization\n- Dosages and effects\n- Synergistic stacks\n- Blood tests to monitor\n\nWhat would you like to know?',
    ia_welcome_nocure: 'I can help you with:\n- Choosing the right peptide for your goals\n- Setting up a complete cycle protocol\n- Understanding dosages and administration routes\n- Creating synergistic stacks\n\nWhat is your question?',

    // ── CALCULATEUR ──────────────────────────────────────────
    calc_title:        'Calculator',
    calc_warning:      'Information tool only',
    calc_warning_sub:  'This calculator is an information tool. Always verify your calculations before any injection. Consult a healthcare professional before any protocol. PeptideScanner disclaims all liability for dosage errors.',
    calc_tab_recon:    '🧪 Reconstitution',
    calc_tab_dosage:   '💉 Dosage',
    calc_tab_titration:'📈 Titration',
    calc_tab_guide:    '📋 Injection guide',
    calc_recon_section:'Step 1 — Calculate concentration',
    calc_recon_title:  '🧪 Vial reconstitution',
    calc_peptide_qty:  'Peptide quantity in vial',
    calc_bac_volume:   'Bacteriostatic water volume to add',
    calc_recon_result: '✓ Reconstitution result',
    calc_dosage_section:'Calculate your precise dose',
    calc_dosage_title: '💉 Precise dose calculator',
    calc_dosage_sub:   'Enter your concentration (calculated in the Reconstitution tab) and desired dose.',
    calc_unit:         'Peptide unit',
    calc_concentration:'Reconstituted vial concentration',
    calc_desired_dose: 'Desired dose',
    calc_syringe:      'Syringe type',
    calc_auto_syringe: '✓ Auto-selected',
    calc_dosage_result:'✓ Dosage result',
    calc_titration_section:'Progressive titration plan',
    calc_guide_section:'Step-by-step injection guide',
    calc_guide_recon:  'Reconstitution steps',
    calc_guide_sc:     'Subcutaneous injection guide',
    calc_guide_warning_title: 'Medical disclaimer',
    calc_guide_warning_sub: 'This guide is for educational purposes only. Any injection must be validated by a healthcare professional. If in doubt, do not proceed. PeptideScanner is not responsible for handling or dosage errors.',
    calc_high_dose_title: 'High dose detected',
    calc_high_dose_confirm: 'I have verified — proceed anyway',
    calc_high_dose_cancel:  '← Recalculate my dose',
    calc_dose_table_dose: 'Dose',
    // ── ANALYTICS ────────────────────────────────────────────
    analytics_title:             'Analytics',
    analytics_30d:               '30 days',
    analytics_60d:               '60 days',
    analytics_90d:               '90 days',
    analytics_all:               'All',
    analytics_scan_score:        'Scan Score',
    analytics_protocol_analysis: 'Protocol analysis',
    analytics_excellent:         'Excellent',
    analytics_good:              'Good',
    analytics_improve:           'To improve',
    analytics_weak:              'Weak',
    analytics_progression:       'Progression',
    analytics_regularity:        'Regularity',
    analytics_insights:          'Automatic insights',
    analytics_cure_day:          'Cycle day',
    analytics_expected:          'expected',
    analytics_pace:              'Pace',
    analytics_kg_week:           'kg / week',
    analytics_over:              'Over',
    analytics_no_data:           'Not enough data to generate insights yet.',
    analytics_no_data_short:     'Not enough data',
    analytics_no_data_help:      'Add at least one active cycle and 2 weight entries.',
    analytics_empty_text:        'Not enough data yet.<br>Start a cycle and log your weight regularly.',
    analytics_start_cure:        'Start a cycle →',
    analytics_heatmap:           'Injection heatmap',
    analytics_weekly_compliance: 'Weekly compliance',
    analytics_weight_proj:       'Weight projection',
    analytics_current_trend:     'Current trend',
    analytics_trend:             'Trend',
    analytics_correlation:       'Weight × time correlation',
    analytics_compliance_excellent: 'Excellent compliance',
    analytics_compliance_good:   'Good compliance',
    analytics_compliance_weak:   'Weak compliance',
    analytics_weekend_drop:      'Compliance drops on weekends',
    analytics_weekend:           'Weekend',
    analytics_weekend_text:      'You are {pct}% less consistent on weekends.',
    analytics_regular_weighing:  'Regular weighing',
    analytics_regular:           'Regular',
    analytics_add_weighing:      'Add more weigh-ins',
    analytics_gap:               'Gap of {n} days without weighing',
    analytics_gap_text:          'You were absent {n} days. Weigh yourself twice a week.',
    analytics_since:             'Since',
    analytics_cure_days_weight:  'days into cycle, your weight has',
    analytics_lost:              'decreased',
    analytics_gained:            'increased',
    analytics_you_lost:          'lost',
    analytics_you_gained:        'gained',
    analytics_missed_inj:        'missed injections',
    analytics_weight_evolution:  'Weight evolution',
    analytics_avg_gap:           'Average gap of',
    analytics_add_weighing_text: 'Goal: 2 weigh-ins per week.',
    analytics_last_days:         'last days',
    analytics_less:              'Less',
    analytics_more:              'More',
    analytics_cure_end:          'Cycle end',
    analytics_remaining_inj:     'Remaining injections',
    analytics_projected_weight:  'Projected weight',
    analytics_projected_diff:    'Projected change',
    analytics_projected_compliance: 'Projected compliance',
    // ── PEPTIDE DATABASE ─────────────────────────────────────
    db_eyebrow:          'Library · Database',
    db_title:            'Complete peptide reference',
    db_sub:              'Every peptide referenced with dosages, protocols, effects and recommended stacks.',
    db_stat_peptides:    'Peptides referenced',
    db_stat_categories:  'Categories',
    db_stat_shown:       'Shown',
    db_search_ph:        'Search peptide, effect, category…',
    db_all:              'All',
    db_cat_recov:        'Recovery',
    db_cat_anti:         'Anti-aging',
    db_cat_neuro:        'Neuro',
    db_cat_fat:          'Weight',
    db_cat_sex:          'Sexual',
    db_cat_immun:        'Immunity',
    db_cat_cardio:       'Cardio',
    db_cat_skin:         'Skin',
    db_guide_title:      '📊 Guide — Research progress',
    db_dosage:           'Dosage',
    db_duration:         'Duration',
    db_stack_with:       'Stack with',
    db_buy:              'Buy →',
    db_no_results_msg:   'No peptide found for "{q}".',
    db_no_results_sub:   'Try a different keyword.',
    db_modal_dosage:     'Typical dosage',
    db_modal_admin:      'Administration',
    db_modal_duration:   'Cycle duration',
    db_modal_freq:       'Frequency',
    db_modal_protocol:   'Detailed protocol',
    db_modal_effects:    'Main effects',
    db_modal_side_effects:'Side effects',
    db_modal_stacks:     'Recommended stacks',
    db_modal_contra:     'Contraindications',
    db_modal_note:       'Expert note',
    db_modal_find:       'Find {name} from a verified supplier',
    db_modal_shops:      'View shops →',
    db_modal_disclaimer: '⚠️ Educational use only. These are research peptides. Always consult a healthcare professional before use.',
    db_disclaimer_title: 'Legal disclaimer — Educational and informational use only.',
    db_disclaimer_body:  'The peptides presented are research peptides. Their acquisition, possession or use may be illegal in your country. The information does not constitute medical advice. Consult a healthcare professional before any protocol.',
    // ── RESEARCH PHASES ──────────────────────────────────────
    phase_exp_label:     'Limited data',
    phase_pre_label:     'Animal research',
    phase_p1_label:      'First human trials',
    phase_p2_label:      'Ongoing studies',
    phase_p3_label:      'Advanced studies',
    phase_est_label:     'Widely used',
    phase_exp_desc:      'Very few studies available',
    phase_pre_desc:      'Tested on animals only',
    phase_p1_desc:       'Safety verified on a few volunteers',
    phase_p2_desc:       'Efficacy tested on hundreds of people',
    phase_p3_desc:       'Tested on thousands — near approval',
    phase_est_desc:      'Abundant feedback, well-documented profile',
    phase_exp_desc_dot:  'Very few studies available.',
    phase_pre_desc_dot:  'Tested on animals only.',
    phase_p1_desc_dot:   'Safety verified on a few volunteers.',
    phase_p2_desc_dot:   'Tested on hundreds of people.',
    phase_p3_desc_dot:   'Tested on thousands — near approval.',
    phase_est_desc_dot:  'Abundant feedback, well-documented profile.',
    phase_step1:         'Research',
    phase_step2:         'Testing',
    phase_step3:         'Studies',
    phase_step4:         'Advanced',
    phase_step5:         'Established',
    // ── INJECTION SITES ──────────────────────────────────────
    site_abd_g:      'Left abdomen',
    site_abd_d:      'Right abdomen',
    site_thigh_g:    'Left thigh',
    site_thigh_d:    'Right thigh',
    site_glute_g:    'Left glute',
    site_glute_d:    'Right glute',
    site_deltoid_g:  'Left deltoid',
    site_deltoid_d:  'Right deltoid',
    site_quad_g:     'Left quadriceps',
    site_quad_d:     'Right quadriceps',
    zone_abdomen:    'Abdomen',
    zone_thigh:      'Thigh',
    zone_glute:      'Glute',
    zone_shoulder:   'Shoulder',
    zone_arm:        'Arm',
    // ── CALCULATEUR TITRATION ────────────────────────────────
    calc_phase_adapt:    'Adaptation phase',
    calc_increase:       'Progressive increase',
    calc_eff_dose:       'Effective dose',
    calc_adv_dose:       'Advanced dose',
    calc_max_dose:       'Maximum dose',
    calc_prog_rise:      'Progressive rise',
    calc_load_phase:     'Loading phase',
    calc_maint_phase:    'Maintenance phase',
    calc_intensive:      'Intensive cycle',
    calc_mandatory_break:'Mandatory break',
    calc_second_cycle:   '2nd annual cycle',
    calc_adapt:          'Adaptation',
    calc_high_dose_label:'High dose',
    calc_warn_bpc_stack: 'Stack with BPC-157 for optimal synergy',
    calc_warn_6months:   'Do not repeat before 6 months',
    calc_warn_2year:     'Maximum 2 cycles per year',
    calc_warn_titration: 'Mandatory titration — never skip steps',
    calc_warn_maxdose:   'Do not exceed 2.4 mg/week without medical supervision',
    calc_approx:         'approximately',
    calc_at_500:         'at 500mcg/day (2×250mcg)',
    calc_sem_s1_exp:     'Possible mild nausea, tolerance assessment',
    calc_sem_s2_exp:     'Noticeable appetite reduction',
    calc_sem_s3_exp:     'Regular weight loss 0.5–1 kg/week',
    calc_sem_s4_exp:     'Accelerated weight loss',
    calc_sem_s5_exp:     'Maximum effect — FDA-approved dose',
    calc_tir_s1_exp:     'Mild nausea, GIP+GLP1 habituation',
    calc_tir_s2_exp:     '↓ Significant appetite reduction',
    calc_bpc_s1_exp:     'Systemic regeneration, improved flexibility, reduced fibrosis',
    calc_bpc_s2_exp:     'Maintaining effects, preventing recurring injuries',
    calc_tb_s1_exp:      'Systemic regeneration',
    calc_epi_s1_exp:     'Telomere lengthening, improved sleep and energy',
    calc_epi_s2_exp:     'Allow time for telomeres to consolidate',
    calc_epi_s3_exp:     'Reinforcement of cumulative anti-aging effects',
    calc_week:           '1×/week',
    calc_warn_semlow:    'If persistent nausea — stay at 0.25mg',
    calc_warn_sem1mg:    'Only if 1mg is well tolerated',
    calc_warn_tol:       'Assess tolerance before increasing',
    calc_warn_prev_tol:  '⚠️ Only if previous doses well tolerated',
    calc_warn_absmax:    '⚠️ Maximum dose — Never exceed',
    calc_warn_exp_p3:    'Experimental peptide — phase 3 clinical trial',
    calc_warn_hr:        'Monitor heart rate (max 100 bpm at rest)',
    calc_warn_exp_only:  '⚠️ Not approved — Research only. Mandatory medical supervision',
    calc_warn_fast:      'Fast for 2h before injection',
    calc_warn_igf1:      'Check IGF-1 at day 30',
    calc_warn_no_continuous: '⚠️ Do not use continuously without a break',
    calc_warn_inject_near:   'Inject near the area to treat',
    calc_appetite_down:  '↓ Appetite',
    calc_fat_loss:       'Fat loss',
    calc_major_loss:     'Major loss',
    calc_max_effect:     'Maximum effect',
    calc_intro:          'Introduction',
    calc_eff_phase:      'Effective phase',
    calc_opt_dose:       'Optimal dose',
    calc_cycle_off:      'Mandatory OFF cycle',
    calc_break_4w:       '4-week break',
    calc_break_6m:       '6-month break',
    calc_2nd_cycle:      '2nd cycle',
    calc_therap_phase:   'Therapeutic phase',
    calc_tir_s3_exp:     'Rapid weight loss, blood sugar improvement',
    calc_tir_s4_exp:     'Maximum effects on body composition',
    calc_tir_s5_exp:     'Optimal results for most patients',
    calc_tir_s6_exp:     'Maximum approved dose — maintain if well tolerated',
    calc_ret_s1_exp:     'Mild nausea, body habituation',
    calc_ret_s2_exp:     'Clear appetite reduction, early weight loss',
    calc_ret_s3_exp:     'Visible visceral fat loss, improved energy',
    calc_ret_s4_exp:     'Significant weight loss, body recomposition',
    calc_ret_s5_exp:     'Maximum results from phase 2 clinical studies',
    calc_cjc_s1_exp:     'Adaptation, possible mild flush, better sleep from day 3-5',
    calc_cjc_s2_exp:     '↑ Nocturnal GH, improved recovery, body composition',
    calc_cjc_s3_exp:     'Maximum GH effects, lipolysis, deep sleep',
    calc_cjc_s4_exp:     'Allow recovery of natural GH axis',
    calc_bpc_intro_exp:  'First anti-inflammatory effects, pain reduction day 5-10',
    calc_bpc_therap_exp: 'Tissue regeneration, healing, gastric protection',
    calc_bpc_maint_exp:  'Maintaining effects, consolidating recovery',
  }
};

// ══════════════════════════════════════════════════════════════
// MOTEUR DE TRADUCTION
// ══════════════════════════════════════════════════════════════

/**
 * Retourne la langue active ('fr' ou 'en')
 */
window.PS_getLang = function() {
  return localStorage.getItem('ps_lang') || 'fr';
};

/**
 * Retourne une chaîne traduite
 * @param {string} key
 * @returns {string}
 */
window.t = function(key) {
  const lang = window.PS_getLang();
  return (window.PS_LANG[lang] && window.PS_LANG[lang][key]) ||
         (window.PS_LANG['fr'][key]) ||
         key;
};

/**
 * Change la langue, sauvegarde en localStorage ET Supabase si sb + userId disponibles
 * @param {string} lang - 'fr' | 'en'
 */
window.PS_setLang = async function(lang) {
  if (lang !== 'fr' && lang !== 'en') return;
  localStorage.setItem('ps_lang', lang);
  // Persister dans Supabase si disponible
  if (window._ps_sb && window._ps_userId) {
    try {
      await window._ps_sb.from('profiles').update({ lang }).eq('id', window._ps_userId);
    } catch(e) { /* silencieux */ }
  }
  // Recharger la page pour appliquer (le plus simple et fiable)
  location.reload();
};

/**
 * Charge la langue depuis Supabase (profile.lang) et met à jour localStorage
 * À appeler après auth, en passant sb et userId
 */
window.PS_loadLangFromProfile = function(sb, userId, profileLang) {
  window._ps_sb     = sb;
  window._ps_userId = userId;
  if (profileLang && (profileLang === 'fr' || profileLang === 'en')) {
    const local = localStorage.getItem('ps_lang');
    // Supabase a priorité si pas encore de préférence locale
    if (!local) localStorage.setItem('ps_lang', profileLang);
  }
};

/**
 * Injecte le bouton toggle FR|EN dans un élément topbar
 * @param {string} containerId - id de l'élément où insérer le toggle
 */
window.PS_injectLangToggle = function(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;
  window.PS_renderLangSwitcher();
};
/**
 * Crée ou met à jour le sélecteur de langue FR | EN dans tous les #langToggleBtn
 */
window.PS_renderLangSwitcher = function() {
  const current = window.PS_getLang();
  document.querySelectorAll('#langToggleBtn').forEach(el => {
    el.innerHTML = '';
    el.style.cssText = 'display:flex;align-items:center;gap:0;border-radius:10px;overflow:hidden;border:1px solid var(--border);flex-shrink:0;';
    el.removeAttribute('onclick');

    ['fr','en'].forEach((lang, i) => {
      const btn = document.createElement('button');
      const isActive = current === lang;
      btn.textContent = lang === 'fr' ? '🇫🇷 FR' : '🇬🇧 EN';
      btn.style.cssText = [
        'padding:5px 10px',
        'font-family:inherit',
        'font-size:.72rem',
        'font-weight:700',
        'cursor:pointer',
        'border:none',
        'outline:none',
        'transition:all .15s',
        isActive
          ? 'background:var(--accent);color:#fff;'
          : 'background:var(--surface);color:var(--muted);',
        i === 0 ? 'border-right:1px solid var(--border);' : '',
      ].join(';');
      if (!isActive) {
        btn.onmouseover = () => { btn.style.background='var(--surface2)'; btn.style.color='var(--text)'; };
        btn.onmouseout  = () => { btn.style.background='var(--surface)';  btn.style.color='var(--muted)'; };
      }
      btn.onclick = (e) => { e.stopPropagation(); if(!isActive) window.PS_setLang(lang); };
      el.appendChild(btn);
    });
  });
};


/**
 * Applique toutes les traductions data-i18n sur la page
 * Appelée une fois au chargement, après avoir défini la langue
 */
window.PS_applyI18n = function() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = window.t(key);
    if (val) el.textContent = val;
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    const val = window.t(key);
    if (val) el.placeholder = val;
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    const val = window.t(key);
    if (val) el.title = val;
  });
};
